// Monastery data with English + Hindi audio files
const monasteries = [
  {
     name: "Rumtek Monastery", 
     files: 
     { english: "audios/english/rumtek.mp3", hindi: "audios/hindi/rumtek.mp3" } ,
    captions: { english: "Rumtek Monastery, also known as the Dharma Chakra Centre, is one of the most significant monasteries in Sikkim. Located about 23 kilometers from Gangtok, it sits on a hilltop overlooking the lush valleys and distant snow-clad peaks. Originally built in the mid-1700s by the 9th Karmapa, the monastery was reconstructed in the 1960s by the 16th Karmapa after he came from Tibet, and today it stands as the main seat of the Karma Kagyu lineage of Tibetan Buddhism outside Tibet. The monastery closely resembles the original Kagyu monastery in Tsurphu, Tibet, and holds immense spiritual importance. Inside, visitors can see the Golden Stupa containing the relics of the 16th Karmapa, beautifully decorated prayer halls with murals and thangkas, and a monastic college where monks study philosophy and rituals. The atmosphere is serene, with the sound of chanting, the flutter of prayer flags, and the scent of incense creating a deeply spiritual experience. During special occasions like Losar and the Kagyed dance festival, Rumtek becomes vibrant with masked dances, rituals, and celebrations, offering a glimpse into the living traditions of Tibetan Buddhism..",
         hindi: "रुमटेक मठ, जिसे धर्म चक्र केंद्र के नाम से भी जाना जाता है, सिक्किम के सबसे महत्वपूर्ण मठों में से एक है। गंगटोक से लगभग 23 किलोमीटर की दूरी पर स्थित यह मठ एक पहाड़ी की चोटी पर बसा है, जहाँ से हरे-भरे घाटियों और दूर बर्फ़ से ढकी चोटियों का सुंदर नज़ारा दिखाई देता है। मूल रूप से इसका निर्माण 18वीं शताब्दी के मध्य में 9वें कर्मापा ने किया था, और 1960 के दशक में 16वें कर्मापा ने तिब्बत से आने के बाद इसका पुनर्निर्माण कराया। आज यह तिब्बत के बाहर कर्मा काग्यू परंपरा का मुख्य केंद्र माना जाता है। यह मठ तिब्बत के त्सुर्फू स्थित मूल काग्यू मठ की तरह ही दिखता है और इसका धार्मिक महत्व अत्यंत गहरा है। मठ के अंदर आगंतुकों को 16वें कर्मापा की अस्थियों को संजोए हुए स्वर्ण स्तूप, सुंदर भित्तिचित्रों और थांगका चित्रों से सुसज्जित प्रार्थना कक्ष, और एक भिक्षु विद्यालय (मोनास्टिक कॉलेज) देखने को मिलता है, जहाँ भिक्षु दर्शनशास्त्र और धार्मिक अनुष्ठानों का अध्ययन करते हैं।मठ का वातावरण अत्यंत शांत और आध्यात्मिक है—यहाँ मंत्रोच्चारण की ध्वनि, प्रार्थना के झंडों की फड़फड़ाहट और धूपबत्ती की सुगंध वातावरण को दिव्य बना देती है। विशेष अवसरों पर, जैसे लोसर और काग्येद नृत्य उत्सव, रुमटेक मठ रंग-बिरंगे मुखौटा नृत्यों, अनुष्ठानों और उत्सवों से जीवंत हो उठता है, जो तिब्बती बौद्ध परंपरा की जीवंत झलक प्रस्तुत करता है।"
         },
     },
  { name: "Pemayangtse Monastery",
     files: { english: "audios/english/pemayangtse.mp3", hindi: "audios/hindi/pemayangtse.mp3" }
,
    captions:
     { english: "Pemayangtse Monastery, located near Pelling in West Sikkim, is one of the oldest and most important monasteries in the state. Founded in the late 17th century by Lhatsun Chempo, a revered Buddhist teacher, it belongs to the Nyingma sect of Tibetan Buddhism, the oldest of all Buddhist traditions. The name “Pemayangtse” means “Perfect Sublime Lotus,” reflecting its spiritual purity and significance. The monastery is perched at an altitude of about 2,085 meters, offering breathtaking views of the majestic Kanchenjunga range. Inside, the monastery is adorned with ancient murals, thangkas, sculptures, and a remarkable seven-tiered wooden structure called Sangtok Palri, representing the celestial palace of Guru Padmasambhava. Pemayangtse has historically been closely associated with the royal family of Sikkim, and its monks, known as “ta-tshang,” are considered highly pure and chosen from specific families. Even today, the monastery is a center of meditation, rituals, and annual festivals such as the colorful Cham dance, where monks perform masked dances to symbolize the victory of good over evil. Surrounded by pine forests and serenity, Pemayangtse offers not only a spiritual retreat but also a glimpse into Sikkim’s deep-rooted Buddhist heritage.", 
        hindi: "पेमायंगत्से मठ, जो पश्चिम सिक्किम के पेलिंग के पास स्थित है, राज्य के सबसे पुराने और महत्वपूर्ण मठों में से एक है। इसका निर्माण 17वीं शताब्दी के अंत में प्रतिष्ठित बौद्ध गुरु ल्हात्सुन चेम्पो द्वारा किया गया था। यह तिब्बती बौद्ध धर्म की सबसे प्राचीन परंपरा, निंगमा सम्प्रदाय, से संबंधित है। “पेमायंगत्से” नाम का अर्थ है “पवित्र श्रेष्ठ कमल”, जो इसकी आध्यात्मिक पवित्रता और महत्व को दर्शाता है।लगभग 2,085 मीटर की ऊँचाई पर स्थित यह मठ भव्य कंचनजंगा पर्वत श्रृंखला के अद्भुत दृश्य प्रस्तुत करता है। मठ के भीतर प्राचीन भित्तिचित्र, थांगका चित्र, मूर्तियाँ और एक अद्वितीय सात-स्तरीय लकड़ी की संरचना संगतोक पालरी देखने को मिलती है, जो गुरु पद्मसम्भव के दिव्य महल का प्रतीक है।ऐतिहासिक रूप से पेमायंगत्से मठ का सिक्किम के शाही परिवार से गहरा संबंध रहा है। यहाँ के भिक्षु, जिन्हें “ता-त्शंग” कहा जाता है, विशेष परिवारों से चुने जाते हैं और अत्यंत पवित्र माने जाते हैं। आज भी यह मठ ध्यान, धार्मिक अनुष्ठानों और वार्षिक उत्सवों का केंद्र है। विशेषकर छम नृत्य महोत्सव में भिक्षु रंग-बिरंगे मुखौटे पहनकर नृत्य करते हैं, जो अच्छाई की बुराई पर विजय का प्रतीक है।पाइन के जंगलों और शांति से घिरा पेमायंगत्से मठ न केवल एक आध्यात्मिक आश्रय है, बल्कि सिक्किम की गहराई से जुड़ी बौद्ध विरासत की झलक भी प्रस्तुत करता है।" } },
  {
     name: "Tashiding Monastery", 
     files: { english: "audios/english/Tashiding.mp3",
         hindi: "audios/hindi/Tashiding.mp3" } 
,
    captions: 
    { english: "Tashiding Monastery, located in West Sikkim between Yuksom and Pelling, is one of the most sacred and revered monasteries of the Nyingma sect of Tibetan Buddhism. Founded in the 17th century by the revered lama Ngadak Sempa Chempo, who was one of the three disciples of Guru Lhatsun Chempo, the monastery holds immense spiritual significance. Perched on a hilltop at about 1,460 meters, it offers panoramic views of the surrounding valleys and the snow-capped Kanchenjunga range. Tashiding is considered a powerful place of purification, and it is believed that simply viewing the monastery can wash away sins. The complex is decorated with beautiful stupas, prayer flags, and ancient inscriptions on stone plates known as mani stones, engraved with the sacred mantra “Om Mani Padme Hum.” The highlight of the monastery is the annual Bumchu Festival, during which a sacred pot of holy water is opened and its level is interpreted as a divine prediction for the coming year, attracting pilgrims from across the Himalayas. With its peaceful surroundings, sacred relics, and deep spiritual aura, Tashiding remains a vital center of faith and devotion in Sikkim.",
         hindi: "ताशिडिंग मठ, जो पश्चिम सिक्किम में युकसोम और पेलिंग के बीच स्थित है, तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय का एक अत्यंत पवित्र और पूजनीय मठ है। इसका निर्माण 17वीं शताब्दी में प्रतिष्ठित लामा ङदक सैम्पा चेम्पो ने किया था, जो गुरु ल्हात्सुन चेम्पो के तीन प्रमुख शिष्यों में से एक थे। यह मठ अत्यधिक धार्मिक महत्व रखता है।लगभग 1,460 मीटर की ऊँचाई पर पहाड़ी की चोटी पर स्थित ताशिडिंग से आसपास की घाटियों और बर्फ से ढकी कंचनजंगा पर्वत श्रृंखला के मनमोहक दृश्य दिखाई देते हैं। यह स्थान शुद्धिकरण का एक शक्तिशाली केंद्र माना जाता है, और ऐसा विश्वास है कि केवल इस मठ को देखने मात्र से ही पाप धुल जाते हैं।मठ परिसर सुंदर स्तूपों, प्रार्थना के झंडों और मणि पत्थरों से सुसज्जित है, जिन पर पवित्र मंत्र “ॐ मणि पद्मे हुँ” उत्कीर्ण होता है। इस मठ का सबसे प्रमुख आकर्षण वार्षिक बुमचू उत्सव है। इस अवसर पर एक पवित्र कलश खोला जाता है और उसमें रखे पवित्र जल के स्तर को आने वाले वर्ष की भविष्यवाणी के रूप में देखा जाता है। यह आयोजन हिमालय के विभिन्न हिस्सों से तीर्थयात्रियों को आकर्षित करता है।शांत वातावरण, पवित्र अवशेषों और गहरी आध्यात्मिक ऊर्जा से युक्त ताशिडिंग मठ आज भी सिक्किम में आस्था और भक्ति का एक प्रमुख केंद्र बना हुआ है।" }},
  { name: "Sanga Choeling Monastery", 
    files:
     { english: "audios/english/Sanga.mp3",
         hindi: "audios/hindi/Sanga.mp3" }
,
    captions:
     { english: "Sanga Choeling Monastery, situated on a ridge above Pelling in West Sikkim, is one of the oldest monasteries in the state, belonging to the Nyingma sect of Tibetan Buddhism. Founded in the 17th century by Lama Lhatsun Chempo, the same revered lama who played a key role in spreading Buddhism in Sikkim, it is often referred to as the “place of secret spells.” The monastery stands at an altitude of around 2,000 meters and can only be reached by a short uphill trek through lush forests, which adds to its serene and secluded atmosphere. Built in traditional Tibetan style, Sanga Choeling houses ancient Buddhist scriptures, clay statues, and ornate murals that depict important deities and teachings. Its simplicity and quiet surroundings make it a place more focused on meditation and spiritual practice than grandeur. The monastery also holds great historical significance as it is closely associated with the early spread of Buddhism in the region. From its hilltop, visitors are rewarded with breathtaking views of the snow-clad Kanchenjunga range and the valleys below, making Sanga Choeling both a spiritual retreat and a scenic destination in Sikkim.", 
        hindi: "संगा चोएलिंग मठ, जो पश्चिम सिक्किम के पेलिंग के ऊपर एक पहाड़ी रिज पर स्थित है, राज्य के सबसे पुराने मठों में से एक है और तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है। इसका निर्माण 17वीं शताब्दी में लामा ल्हात्सुन चेम्पो ने किया था, जो सिक्किम में बौद्ध धर्म के प्रसार में महत्वपूर्ण भूमिका निभाने वाले एक पूजनीय संत थे। इस मठ को अक्सर “गुप्त मंत्रों का स्थान” भी कहा जाता है।लगभग 2,000 मीटर की ऊँचाई पर स्थित यह मठ केवल एक छोटी पहाड़ी पगडंडी से होकर पहुँचा जा सकता है, जो हरे-भरे जंगलों से गुजरती है। यही इसे और अधिक शांत और एकांत बनाती है। पारंपरिक तिब्बती शैली में निर्मित इस मठ में प्राचीन बौद्ध ग्रंथ, मिट्टी की मूर्तियाँ और सुसज्जित भित्तिचित्र हैं, जिनमें महत्वपूर्ण देवताओं और उपदेशों को दर्शाया गया है। अपनी सादगी और शांत वातावरण के कारण संगा चोएलिंग मठ भव्यता की तुलना में ध्यान और आध्यात्मिक साधना पर अधिक केंद्रित है। इसका ऐतिहासिक महत्व भी बहुत बड़ा है, क्योंकि यह सिक्किम में बौद्ध धर्म के शुरुआती प्रसार से गहराई से जुड़ा हुआ है।मठ की पहाड़ी चोटी से आगंतुकों को बर्फ से ढकी कंचनजंगा पर्वत श्रृंखला और नीचे की घाटियों का मनोहारी दृश्य दिखाई देता है, जिससे संगा चोएलिंग मठ एक आध्यात्मिक आश्रय स्थल होने के साथ-साथ एक सुंदर पर्यटन स्थल भी बन जाता है।" } },
  { 
    name: "Lachung Monastery",
     files:
      { english: "audios/english/Lachung.mp3",
         hindi: "audios/hindi/Lachung.mp3" }
,
    captions: 
    { english: "Lachung is a scenic village in North Sikkim, perched at an altitude of around 2,700 meters and surrounded by snow-covered mountains, waterfalls, and fruit orchards. Its name means “small pass,” and the village lies at the meeting point of the Lachung and Lachen rivers, both tributaries of the Teesta. Known for its breathtaking beauty, Lachung is the gateway to the famous Yumthang Valley, often called the “Valley of Flowers,” which bursts into color with alpine blooms during spring. The village is also home to the Lachung Monastery, built in the 19th century, which belongs to the Nyingma sect of Tibetan Buddhism and adds to the spiritual atmosphere of the region. What makes Lachung culturally unique is the presence of the Lachungpas, the local people who follow a traditional self-governing system known as the Zumsa, where villagers collectively make decisions for the community. Apart from its rich traditions, the village is known for its apple orchards, handicrafts, and warm hospitality. Lachung also serves as a base for exploring hot springs, high-altitude lakes, and trekking routes further into the Himalayas. With its mix of natural beauty, cultural richness, and serene environment, Lachung is often described as one of the most enchanting destinations in Sikkim.",
         hindi: "लाचुंग उत्तर सिक्किम का एक खूबसूरत गाँव है, जो लगभग 2,700 मीटर की ऊँचाई पर बसा हुआ है। यह गाँव बर्फ से ढके पहाड़ों, झरनों और फलों के बागों से घिरा हुआ है। लाचुंग का अर्थ है “छोटा दर्रा”, और यह गाँव लाचुंग तथा लाचेन नदियों के संगम पर स्थित है, जो दोनों ही तीस्ता नदी की सहायक नदियाँ हैं। अपनी अद्भुत प्राकृतिक सुंदरता के लिए प्रसिद्ध लाचुंग को अक्सर युमथांग घाटी का प्रवेशद्वार माना जाता है। युमथांग घाटी, जिसे “फूलों की घाटी” भी कहा जाता है, वसंत ऋतु में खिले अल्पाइन फूलों से रंग-बिरंगी हो उठती है। गाँव का प्रमुख आकर्षण लाचुंग मठ है, जिसका निर्माण 19वीं शताब्दी में हुआ था और यह निंगमा सम्प्रदाय से संबंधित है, जो इस क्षेत्र के आध्यात्मिक वातावरण को और भी गहरा बनाता है।लाचुंग की सांस्कृतिक विशिष्टता लाचुंगपा समुदाय है। यहाँ के लोग एक पारंपरिक स्वशासी तंत्र जुमसा (Zumsa) का पालन करते हैं, जिसके अंतर्गत ग्रामीण सामूहिक रूप से समुदाय से जुड़े निर्णय लेते हैं। अपनी इस परंपरा के अलावा यह गाँव सेब के बागानों, हस्तशिल्प और अपनी गर्मजोशी भरी मेहमाननवाज़ी के लिए भी जाना जाता है। लाचुंग गर्म पानी के झरनों, ऊँचाई वाले हिमालयी झीलों और ट्रेकिंग मार्गों की खोज का भी आधार स्थल है। अपनी प्राकृतिक सुंदरता, सांस्कृतिक समृद्धि और शांत वातावरण के मेल से लाचुंग को सिक्किम के सबसे मोहक पर्यटन स्थलों में गिना जाता है।" } },
  { name: "Ralong Monastery",
     files: 
     { english: "audios/english/Ralong.mp3", hindi: "audios/hindi/Ralong.mp3" } 
,
    captions:
     { english: "Ralong Monastery, located near Ravangla in South Sikkim, is one of the most important centers of the Kagyu sect of Tibetan Buddhism. It is believed to have been established in the 18th century after the fourth Chogyal of Sikkim built it to commemorate his successful pilgrimage to Tibet. The monastery is closely associated with the Karmapa, the head of the Karma Kagyu lineage, and holds a strong spiritual connection to the Rumtek Monastery. The monastery complex is adorned with traditional Tibetan architecture, vibrant murals, prayer wheels, and statues of Buddhist deities. It is particularly famous for its grand annual festival called the Pang Lhabsol, during which monks perform the spectacular Cham masked dances, symbolizing the triumph of good over evil. The serene location of Ralong, surrounded by mountains, forests, and sweeping views of the Himalayas, adds to its spiritual charm. Nearby, the New Ralong Monastery, built in the 1990s, stands as a larger and more modern structure, yet it retains the essence of Buddhist tradition. Together, the old and new monasteries make Ralong a significant pilgrimage site, offering visitors a chance to experience Sikkim’s deep-rooted Buddhist culture amid a peaceful and scenic setting.", 
        hindi: "रालोंग मठ, जो दक्षिण सिक्किम के रावंगला के पास स्थित है, तिब्बती बौद्ध धर्म की काग्यू सम्प्रदाय का एक प्रमुख केंद्र है। ऐसा माना जाता है कि इसका निर्माण 18वीं शताब्दी में सिक्किम के चौथे चोग्याल ने तिब्बत की अपनी सफल तीर्थयात्रा की स्मृति में करवाया था। यह मठ कर्मापा, जो कर्मा काग्यू परंपरा के प्रमुख हैं, से गहराई से जुड़ा हुआ है और इसका आध्यात्मिक संबंध रुमटेक मठ से भी विशेष माना जाता है।मठ परिसर पारंपरिक तिब्बती वास्तुकला, रंग-बिरंगे भित्तिचित्रों, प्रार्थना चक्करों और बौद्ध देवताओं की मूर्तियों से सुसज्जित है। यह विशेष रूप से अपने भव्य वार्षिक उत्सव पांग ल्हाबसोल के लिए प्रसिद्ध है, जिसमें भिक्षु आकर्षक छम नृत्य (मुखौटा नृत्य) प्रस्तुत करते हैं, जो अच्छाई की बुराई पर विजय का प्रतीक है। रालोंग का शांत वातावरण, जो पर्वतों, जंगलों और हिमालय के विस्तृत दृश्यों से घिरा हुआ है, इसकी आध्यात्मिक आभा को और भी बढ़ा देता है।इसके निकट ही 1990 के दशक में निर्मित नया रालोंग मठ स्थित है, जो आकार में बड़ा और अधिक आधुनिक है, फिर भी इसमें बौद्ध परंपरा की मूल भावना समाई हुई है। पुराना और नया रालोंग मठ मिलकर इस स्थान को एक महत्वपूर्ण तीर्थस्थल बनाते हैं, जहाँ आगंतुक शांतिपूर्ण और प्राकृतिक परिवेश में सिक्किम की गहरी बौद्ध संस्कृति का अनुभव कर सकते हैं।" }},
  { name: "Kewzing Monastery", 
    files:
     { english: "audios/english/Kewzing.mp3", 
        hindi: "audios/hindi/Kewzing.mp3" }
,
    captions: 
    { english: "Kewzing is a quiet and picturesque village in South Sikkim, located about 10 kilometers from Ravangla, known for its natural beauty, traditional lifestyle, and Buddhist heritage. Nestled at an altitude of around 1,400 meters, it offers stunning views of the snow-clad Kanchenjunga range and is surrounded by dense forests rich in flora and fauna. The village is home to the Bon Monastery (also called Kewzing Monastery), one of the very few monasteries in India that follows the ancient Bon tradition, which predates Buddhism in Tibet. This makes Kewzing an important spiritual destination, giving visitors a rare glimpse into unique rituals and practices that are different from mainstream Buddhist traditions.Kewzing is also known for its eco-tourism and homestay culture, where travelers can stay with local families, experience Sikkimese hospitality, taste traditional food, and learn about the customs of the Bhutia community. The village is a haven for birdwatchers, with over 200 species of birds found in its forests, including rare pheasants and Himalayan species. Treks from Kewzing lead to nearby monasteries like Doling, Ravangla, and Tashiding, as well as scenic trails through cardamom plantations and forests. With its blend of spirituality, nature, and authentic village life, Kewzing is often described as a hidden gem for those seeking peace, culture, and connection with nature in Sikkim.",
         hindi: "क्यूजिंग दक्षिण सिक्किम का एक शांत और सुरम्य गाँव है, जो रावंगला से लगभग 10 किलोमीटर की दूरी पर स्थित है। यह अपनी प्राकृतिक सुंदरता, पारंपरिक जीवनशैली और बौद्ध विरासत के लिए प्रसिद्ध है। लगभग 1,400 मीटर की ऊँचाई पर बसा यह गाँव बर्फ से ढकी कंचनजंगा पर्वत श्रृंखला के अद्भुत दृश्य प्रस्तुत करता है और चारों ओर घने जंगलों से घिरा है, जिनमें समृद्ध वनस्पति और जीव-जंतु पाए जाते हैं।क्यूजिंग का मुख्य आकर्षण बोन मठ (जिसे क्यूजिंग मठ भी कहा जाता है) है, जो भारत के उन गिने-चुने मठों में से एक है जहाँ प्राचीन बोन परंपरा का पालन किया जाता है। यह परंपरा तिब्बत में बौद्ध धर्म से भी पूर्व की है, जिसके कारण यह मठ एक महत्वपूर्ण आध्यात्मिक गंतव्य माना जाता है। यहाँ आने वाले आगंतुकों को मुख्यधारा के बौद्ध धर्म से अलग अद्वितीय अनुष्ठानों और परंपराओं की झलक देखने को मिलती है।क्यूजिंग ईको-टूरिज्म और होमस्टे संस्कृति के लिए भी प्रसिद्ध है। यहाँ यात्री स्थानीय परिवारों के साथ रहकर सिक्किमी आतिथ्य का अनुभव कर सकते हैं, पारंपरिक भोजन का स्वाद ले सकते हैं और भूटिया समुदाय की रीति-रिवाजों को करीब से जान सकते हैं। यह गाँव पक्षी प्रेमियों के लिए भी स्वर्ग समान है, क्योंकि इसके जंगलों में 200 से अधिक प्रजातियों के पक्षी पाए जाते हैं, जिनमें दुर्लभ तीतर और हिमालयी प्रजातियाँ शामिल हैं।क्यूजिंग से कई ट्रेक मार्ग भी निकलते हैं, जो डोलिंग, रावंगला और ताशिडिंग जैसे निकटवर्ती मठों तक ले जाते हैं। इसके अलावा इलायची के खेतों और जंगलों से होकर जाने वाले सुंदर मार्ग भी यहाँ से शुरू होते हैं। आध्यात्मिकता, प्रकृति और प्रामाणिक ग्रामीण जीवन के इस अनोखे संगम के कारण क्यूजिंग को अक्सर सिक्किम का “छुपा हुआ रत्न” कहा जाता है।" } },
  { name: "Ben Monastery",
     files: 
     { english: "audios/english/Ben.mp3",
         hindi: "audios/hindi/Ben.mp3" } 
,
    captions:
     { english: "Ben is a small, serene village in South Sikkim, not far from Ravangla, known for its peaceful surroundings and deep spiritual atmosphere. It is especially significant for the Ben Monastery, which belongs to the Nyingma sect of Tibetan Buddhism. The monastery, though modest in size compared to some of Sikkim’s larger ones, holds great importance as a center for local religious and cultural life. It is beautifully set against the backdrop of rolling hills and forests, making it a tranquil spot for meditation and prayer. The village of Ben itself offers an authentic experience of rural Sikkimese life. Surrounded by terraced fields, cardamom plantations, and traditional houses, it provides visitors with a chance to enjoy simplicity and natural beauty. The area around Ben is also rich in trekking and walking trails that connect it with other monasteries and villages in the region, giving a glimpse into Sikkim’s interconnected spiritual landscape. With its quiet charm, religious heritage, and scenic setting, Ben is often described as a hidden corner of Sikkim where both spirituality and nature exist in perfect harmony.",
         hindi: "बेन् दक्षिण सिक्किम का एक छोटा और शांत गाँव है, जो रावंगला के निकट स्थित है और अपने शांत वातावरण तथा गहरी आध्यात्मिक आभा के लिए जाना जाता है। इसका विशेष महत्व बेन् मठ से है, जो तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है। आकार में यह मठ सिक्किम के बड़े मठों की तुलना में छोटा है, लेकिन स्थानीय धार्मिक और सांस्कृतिक जीवन का एक महत्वपूर्ण केंद्र माना जाता है। चारों ओर फैली पहाड़ियों और जंगलों की पृष्ठभूमि में स्थित यह मठ ध्यान और प्रार्थना के लिए एक अत्यंत शांत और पवित्र स्थान प्रदान करता है। स्वयं बेन् गाँव भी ग्रामीण सिक्किमी जीवन का एक प्रामाणिक अनुभव कराता है। सीढ़ीदार खेतों, इलायची की खेती और पारंपरिक घरों से घिरा यह गाँव आगंतुकों को सादगी और प्राकृतिक सुंदरता का आनंद लेने का अवसर देता है। बेन् के आसपास का क्षेत्र ट्रेकिंग और वॉकिंग ट्रेल्स से भी समृद्ध है, जो इसे अन्य मठों और गाँवों से जोड़ते हैं। इस प्रकार यह सिक्किम की आपस में जुड़ी हुई आध्यात्मिक धरोहर की झलक प्रस्तुत करता है।अपनी शांति, धार्मिक महत्व और प्राकृतिक परिवेश के मेल से बेन् को अक्सर सिक्किम का एक ऐसा छिपा हुआ कोना कहा जाता है, जहाँ आध्यात्मिकता और प्रकृति का अद्भुत संतुलन देखने को मिलता है।" }},
  { name: "Enchey Monastery", 
    files: { english: "audios/english/Enchey.mp3",
         hindi: "audios/hindi/Enchey.mp3" } 
,
    captions: 
    { english: "Enchey Monastery, also known as Enchey Sangag Rabtenling, is a revered Buddhist monastery situated approximately 3 kilometers northeast of Gangtok, the capital city of Sikkim, India. Established in 1840 by Lama Drupthob Karpo, a tantric master renowned for his flying abilities, the monastery is affiliated with the Nyingma sect of Tibetan Buddhism The monasterys name, Enchey, translates to Solitary, reflecting its serene and isolated location amidst pine forests. According to local legend, Lama Drupthob Karpo flew from Maenam Hill in South Sikkim to this site, blessing it as a sacred place for spiritual practice. The current structure, built in 1909 during the reign of the 10th Chogyal, Sikyong Tulku, showcases traditional Tibetan architectural elements, including ornate prayer wheels and vibrant murals depicting Buddhist deities Enchey Monastery holds significant religious importance, with local belief attributing the presence of protective deities such as Khangchendzonga and Yabdean within its premises. These deities are said to fulfill the wishes of devotees who visit the monastery with sincere hearts. The monastery is also renowned for its vibrant festivals, notably the Detor Cham dance, held annually on the 18th and 19th days of the 12th lunar month of the Tibetan calendar, corresponding to January or February. This Cham dance features masked performances symbolizing the subjugation of evil spirits and is a major attraction for both locals and tourists. Visitors to Enchey Monastery can experience a tranquil environment conducive to meditation and reflection, offering panoramic views of the surrounding landscapes and a glimpse into the rich spiritual heritage of Sikkim.", 
        hindi: "एंचे मठ, जिसे एंचे संगग रब्तेनलिंग भी कहा जाता है, सिक्किम की राजधानी गंगटोक से लगभग 3 किलोमीटर उत्तर-पूर्व में स्थित एक प्रतिष्ठित बौद्ध मठ है। इसकी स्थापना वर्ष 1840 में लामा द्रुपथोब कार्पो ने की थी, जो अपनी तांत्रिक साधनाओं और उड़ने की अद्भुत क्षमता के लिए प्रसिद्ध थे। यह मठ निंगमा सम्प्रदाय से संबंधित है। “एंचे” शब्द का अर्थ है एकांत, जो देवदार के जंगलों के बीच इसके शांत और अलग-थलग स्थान को दर्शाता है। स्थानीय किंवदंती के अनुसार, लामा द्रुपथोब कार्पो दक्षिण सिक्किम के मैनम पहाड़ी से उड़कर यहाँ आए थे और इस स्थल को आध्यात्मिक साधना के लिए पवित्र बना दिया।वर्तमान संरचना का निर्माण वर्ष 1909 में 10वें चोग्याल, सिक्योंग तुल्कु के शासनकाल में हुआ था। इसमें पारंपरिक तिब्बती स्थापत्य शैली दिखाई देती है, जिसमें अलंकृत प्रार्थना चक्र और रंग-बिरंगे भित्ति चित्र शामिल हैं, जिनमें बौद्ध देवताओं का चित्रण है। एंचे मठ धार्मिक दृष्टि से अत्यंत महत्वपूर्ण माना जाता है, क्योंकि स्थानीय मान्यता है कि यहाँ खांगचेंदजोंगा और यब्देन जैसे संरक्षक देवताओं का वास है। कहा जाता है कि ये देवता श्रद्धालु भक्तों की सच्चे मन से की गई प्रार्थनाएँ पूरी करते हैं मठ अपने भव्य उत्सवों के लिए भी प्रसिद्ध है, विशेषकर डेटोर छम नामक नृत्य महोत्सव के लिए, जो तिब्बती पंचांग के 12वें महीने की 18वीं और 19वीं तिथि को (जनवरी या फ़रवरी में) आयोजित होता है। इस दौरान साधु-भिक्षु मुखौटा पहनकर नृत्य करते हैं, जो दुष्ट आत्माओं के दमन का प्रतीक है। यह पर्व स्थानीय लोगों और पर्यटकों दोनों के लिए आकर्षण का केंद्र है।एंचे मठ आने वाले आगंतुकों को ध्यान और चिंतन के लिए उपयुक्त शांत वातावरण प्रदान करता है। साथ ही यहाँ से आसपास के प्राकृतिक दृश्यों का मनमोहक दर्शन और सिक्किम की समृद्ध आध्यात्मिक धरोहर की झलक मिलती है।" }},
  { name:
     "Lingdum Monastery",
      files: { english: "audios/english/Lingdum.mp3", 
        hindi: "audios/hindi/Lingdum.mp3" } 
,
    captions:
     { english: "Lingdum Monastery, also known as **Ranka Monastery**, is a relatively new but grand monastery located about 20 kilometers from Gangtok in East Sikkim. Belonging to the Zurmang Kagyu sect of Tibetan Buddhism, it was built in the late 20th century and has quickly become one of the most impressive monasteries in the region, both for its scale and architectural beauty. The monastery is modeled in traditional Tibetan style, with a massive prayer hall adorned with vibrant murals, thangkas, and intricate woodwork depicting Buddhist teachings and deities. The monastery is home to a large number of young monks who undergo rigorous spiritual and academic training. Visitors can often see them engaged in prayers, debates, or monastic rituals, offering a glimpse into the disciplined life of Buddhist practitioners. The peaceful surroundings, with forests and hills encircling the monastery, add to its spiritual atmosphere, making it an ideal place for meditation and reflection. Lingdum Monastery is also known for its festivals, particularly during Losar (Tibetan New Year), when sacred Cham dances are performed with colorful masks and costumes. With its majestic architecture, serene environment, and vibrant spiritual life, Lingdum stands as both a cultural treasure and a serene retreat for those exploring Sikkim’s Buddhist heritage.",
         hindi: "लिंगडुम मठ, जिसे रंका मठ भी कहा जाता है, पूर्वी सिक्किम में गंगटोक से लगभग 20 किलोमीटर दूर स्थित एक भव्य और अपेक्षाकृत नया मठ है। यह ज़ुर्मंग काग्यु सम्प्रदाय से संबंधित है और इसका निर्माण 20वीं शताब्दी के उत्तरार्ध में किया गया था। अपनी विशालता और स्थापत्य सौंदर्य के कारण यह क्षेत्र के सबसे प्रभावशाली मठों में से एक बन चुका है। यह मठ पारंपरिक तिब्बती शैली में निर्मित है। विशाल प्रार्थना-सभा भवन में रंग-बिरंगे भित्तिचित्र, थंका चित्रकला और बारीक नक्काशी की गई काष्ठकला देखने योग्य है, जिनमें बौद्ध शिक्षाओं और देवताओं का चित्रण किया गया है। मठ में बड़ी संख्या में युवा भिक्षु रहते हैं, जो कठोर आध्यात्मिक और शैक्षणिक प्रशिक्षण प्राप्त करते हैं। आगंतुक अक्सर उन्हें प्रार्थना, वाद-विवाद या धार्मिक अनुष्ठानों में संलग्न देख सकते हैं, जिससे बौद्ध साधना और अनुशासित जीवन की झलक मिलती है। मठ का शांत वातावरण, जिसे चारों ओर से पहाड़ों और जंगलों ने घेरा हुआ है, इसकी आध्यात्मिकता को और गहरा बना देता है, जिससे यह ध्यान और चिंतन के लिए एक आदर्श स्थान बन जाता है। लिंगडुम मठ अपने त्योहारों के लिए भी प्रसिद्ध है, विशेषकर लोसर (तिब्बती नववर्ष) के अवसर पर, जब यहाँ रंग-बिरंगे मुखौटों और पोशाकों के साथ पवित्र छम नृत्य प्रस्तुत किए जाते हैं।अपनी भव्य वास्तुकला, शांत वातावरण और जीवंत आध्यात्मिक जीवन के साथ, लिंगडुम मठ सिक्किम की बौद्ध विरासत का एक सांस्कृतिक खजाना और आध्यात्मिक शरणस्थल दोनों माना जाता है।" }},
  { name:
     "Do Drul Chorten Monastery",
      files: { english: "audios/english/Do.mp3", hindi: "audios/hindi/Do.mp3" } 
,
    captions:
     { english: "The Do Drul Chorten in Gangtok, Sikkim, is a highly revered Buddhist stupa and a popular pilgrimage site. It was built in 1945–46 under the guidance of Trulshik Rinpoche, a respected lama of the Nyingma order of Tibetan Buddhism. The stupa was constructed to ward off evil spirits and promote peace, harmony, and spiritual well-being. Surrounding the stupa are 108 prayer wheels, which devotees spin while chanting the sacred mantra “Om Mani Padme Hum” as they walk around it in a clockwise direction. Inside the stupa are sacred relics, religious texts, and spiritual objects, making it a powerful symbol of faith. The atmosphere around Do Drul Chorten is serene, offering visitors a sense of calm and devotion. Situated close to the Namgyal Institute of Tibetology, it is not only a place of worship but also a cultural landmark that draws both devotees and tourists alike",
         hindi: "दो द्रुल चोर्टेन, गंगटोक (सिक्किम) में स्थित, एक अत्यंत पूजनीय बौद्ध स्तूप और प्रमुख तीर्थस्थल है। इसका निर्माण वर्ष 1945–46 में निंगमा सम्प्रदाय के आदरणीय लामा त्रुलशिक रिनपोछे के मार्गदर्शन में किया गया था। इस स्तूप का निर्माण दुष्ट आत्माओं को दूर करने और शांति, सद्भाव तथा आध्यात्मिक कल्याण को बढ़ावा देने के उद्देश्य से किया गया था।स्तूप के चारों ओर 108 प्रार्थना चक्र (मणि-पत्थर) लगे हुए हैं, जिन्हें श्रद्धालु “ॐ मणि पद्मे हुं” मंत्र का जाप करते हुए दक्षिणावर्त दिशा में घुमाते हैं। स्तूप के भीतर पवित्र अवशेष, धार्मिक ग्रंथ और आध्यात्मिक वस्तुएँ सुरक्षित हैं, जो इसे आस्था का एक शक्तिशाली प्रतीक बनाती हैं।दो द्रुल चोर्टेन के आसपास का वातावरण अत्यंत शांत और आध्यात्मिक अनुभूति से भरा होता है, जहाँ आगंतुक गहन श्रद्धा और शांति का अनुभव करते हैं। यह स्थल नामग्याल इंस्टीट्यूट ऑफ़ तिबेटोलॉजी के निकट स्थित है, जिसके कारण यह न केवल एक पूजनीय धार्मिक स्थल है बल्कि एक सांस्कृतिक धरोहर भी है, जो भक्तों और पर्यटकों दोनों को आकर्षित करता है।" }},
  { name: "Dubdi Monastery",
     files: { english: "audios/english/Dubdi.mp3", hindi: "audios/hindi/Dubdi.mp3" } 
,
    captions:
     { english: "The Dubdi Monastery, located near Yuksom in West Sikkim, is one of the oldest and most historic monasteries in the state. Built in 1701 by Lhatsun Namkha Jigme, a revered lama of the Nyingma sect, it is often called the “Hermit’s Cell.” The monastery holds special significance as Yuksom was the first capital of Sikkim and the place where the first Chogyal (king) was consecrated. Perched on a hilltop at about 2,100 meters, Dubdi Monastery offers panoramic views of the surrounding mountains and forests. Architecturally, it is a two-story stone structure with a tapering tower, painted walls, and a collection of rare manuscripts, images of Buddhist deities, and sacred objects. It remains an important pilgrimage site for Buddhists and a symbol of Sikkim’s deep-rooted spiritual and cultural heritage.",
         hindi: "डुबडी मठ, पश्चिम सिक्किम के युकसोम के पास स्थित, राज्य के सबसे प्राचीन और ऐतिहासिक मठों में से एक है। इसका निर्माण वर्ष 1701 में निंगमा सम्प्रदाय के आदरणीय लामा ल्हात्सुन नामखा जिग्मे द्वारा किया गया था। इसे अक्सर “सन्यासी की कुटिया” (Hermit’s Cell) भी कहा जाता है। यह मठ विशेष महत्व रखता है क्योंकि युकसोम सिक्किम की पहली राजधानी थी और यहीं पर पहले चोग्याल (राजा) का अभिषेक हुआ था।लगभग 2,100 मीटर की ऊँचाई पर पहाड़ी की चोटी पर स्थित यह मठ चारों ओर फैले पर्वतों और वनों के मनोरम दृश्य प्रस्तुत करता है। स्थापत्य की दृष्टि से यह दो-मंज़िला पत्थर की इमारत है, जिसमें एक शिखरदार टावर, रंगीन चित्रित दीवारें, दुर्लभ पांडुलिपियाँ, बौद्ध देवताओं की मूर्तियाँ और पवित्र वस्तुएँ संरक्षित हैं।डुबडी मठ आज भी बौद्ध श्रद्धालुओं के लिए एक महत्वपूर्ण तीर्थस्थल है और सिक्किम की गहरी जड़ें जमाई आध्यात्मिक तथा सांस्कृतिक धरोहर का प्रतीक बना हुआ है।" }},
  { name: "Kheocheolpalri Monastery",
     files: { english: "audios/english/Kheocheolpalri.mp3", 
        hindi: "audios/hindi/Kheocheolpalri.mp3" }
,
    captions: 
    { english: "The Khecheopalri Monastery, situated close to the famous Khecheopalri Lake in West Sikkim, is an important Buddhist pilgrimage site belonging to the Nyingma sect of Tibetan Buddhism. Built amidst dense forests and hills, the monastery is often visited together with the lake, which is considered sacred by both Buddhists and Hindus. According to legend, the lake and the monastery are associated with the goddess Tara, and it is believed that wishes made here are fulfilled. The monastery itself, though small in size, holds deep spiritual importance for the local community. It is adorned with colorful prayer flags and traditional Buddhist paintings, creating an atmosphere of peace and devotion. Each year, the monastery hosts major religious events, such as the Chho-Tsho festival, during which monks and devotees gather to perform prayers and rituals for peace and prosperity. Pilgrims circumambulate the lake and visit the monastery to seek blessings, spin prayer wheels, and participate in chanting sessions. Surrounded by natural beauty and silence, the Khecheopalri Monastery, along with the lake, symbolizes the harmony of spirituality and nature, making it a must-visit site for both devotees and travelers exploring Sikkim’s cultural heritage.", 
        hindi: "खেচियोपलरी मठ, पश्चिम सिक्किम में प्रसिद्ध खেচियोपलरी झील के पास स्थित, निंगमा सम्प्रदाय का एक महत्वपूर्ण बौद्ध तीर्थस्थल है। घने जंगलों और पहाड़ियों के बीच बना यह मठ प्रायः झील के साथ ही दर्शन हेतु जाया जाता है, क्योंकि झील को बौद्ध और हिंदू दोनों ही पवित्र मानते हैं।किंवदंती के अनुसार, झील और मठ का संबंध देवी तारा से है और यह विश्वास किया जाता है कि यहाँ माँगी गई मनोकामनाएँ पूर्ण होती हैं। आकार में भले ही छोटा हो, लेकिन यह मठ स्थानीय समुदाय के लिए अत्यंत आध्यात्मिक महत्व रखता है। इसे रंग-बिरंगे प्रार्थना-ध्वजों और पारंपरिक बौद्ध चित्रों से सजाया गया है, जो वातावरण को शांति और भक्ति से भर देता है।हर वर्ष यहाँ छो-छो महोत्सव जैसे प्रमुख धार्मिक आयोजन होते हैं, जिनमें भिक्षु और श्रद्धालु शांति और समृद्धि के लिए प्रार्थनाएँ और अनुष्ठान करते हैं। तीर्थयात्री झील की परिक्रमा करते हैं, मठ में आशीर्वाद लेने आते हैं, प्रार्थना चक्र घुमाते हैं और सामूहिक मंत्रोच्चार में भाग लेते हैं।प्राकृतिक सौंदर्य और गहन शांति से घिरा खেচियोपलरी मठ और झील आध्यात्मिकता और प्रकृति के अद्भुत सामंजस्य का प्रतीक है, जो श्रद्धालुओं और यात्रियों दोनों के लिए सिक्किम की सांस्कृतिक धरोहर का एक अविस्मरणीय स्थल है।" } },
  { name: 
    "Malam Monastery",
     files: { english: "audios/english/Malam.mp3",
         hindi: "audios/hindi/Malam.mp3" }
,
    captions:
     { english: "Malam Monastery, also known as Maalam Monastery, is a significant Buddhist monastery located in North Sikkim, India. Established in 1928 by the Lepcha community, it stands as a testament to the region's rich spiritual heritage. The monastery follows the Nyingma sect of Tibetan Buddhism and is situated on a hilltop near Phensang Monastery, approximately 9 kilometers north of Gangtok The monastery's architecture reflects traditional Tibetan designs, featuring intricately painted walls, vibrant murals, and statues of various Buddhist deities. These artistic elements not only enhance the spiritual ambiance but also serve as visual narratives of Buddhist teachings and legends.Malam Monastery continues to serve as a center for Buddhist teachings and practices, attracting pilgrims and tourists alike who seek spiritual solace and a deeper understanding of Sikkim's rich cultural heritage. The serene environment, coupled with the monastery's historical and spiritual importance, makes it a noteworthy destination for those interested in exploring the Buddhist traditions of the region.", 
        hindi: "मालाम मठ, जिसे मालाम मठ (Maalam Monastery) भी कहा जाता है, सिक्किम के उत्तरी भाग में स्थित एक प्रमुख बौद्ध मठ है। इसका निर्माण वर्ष 1928 में लेपचा समुदाय द्वारा किया गया था, और यह क्षेत्र की समृद्ध आध्यात्मिक धरोहर का एक महत्वपूर्ण प्रतीक है। यह मठ निंगमा सम्प्रदाय का अनुयायी है और फेंसांग मठ के पास, गंगटोक से लगभग 9 किलोमीटर उत्तर की ओर एक पहाड़ी पर स्थित है। मठ की वास्तुकला पारंपरिक तिब्बती शैली को दर्शाती है। यहाँ की दीवारों पर जटिल चित्रकारी, जीवंत भित्तिचित्र (murals) और विभिन्न बौद्ध देवताओं की मूर्तियाँ सजाई गई हैं। ये कलात्मक तत्व न केवल आध्यात्मिक वातावरण को और गहन बनाते हैं, बल्कि बौद्ध शिक्षाओं और दंतकथाओं का दृश्य रूप में वर्णन भी करते हैं। आज भी मालाम मठ बौद्ध शिक्षाओं और साधना का केंद्र बना हुआ है। यह तीर्थयात्रियों और पर्यटकों दोनों को आकर्षित करता है, जो यहाँ शांति, आस्था और सिक्किम की समृद्ध सांस्कृतिक धरोहर की गहरी समझ प्राप्त करना चाहते हैं। इसकी शांत प्राकृतिक पृष्ठभूमि, ऐतिहासिक और धार्मिक महत्व के साथ मिलकर, इसे सिक्किम की बौद्ध परंपराओं को जानने के इच्छुक लोगों के लिए एक विशेष गंतव्य बनाती है।" } },
  { name: "Line Phagyal Monastery",
     files:
      { english: "audios/english/Line.mp3",
         hindi: "audios/hindi/Line.mp3" } 
,
    captions:
     { english: "The Linge (Lingee) Phagyal Monastery, founded in 1862 A.D. by Lama Phagyal, is an important Nyingma sect monastery located in South Sikkim. It stands as one of the older monasteries in the region, built to serve the spiritual needs of the local Buddhist community. Belonging to the ancient Nyingma school of Tibetan Buddhism, the monastery preserves traditional practices, teachings, and rituals passed down for generations. Surrounded by the serene natural beauty of South Sikkim, it offers a peaceful environment for prayer and meditation. Though not as widely known as some of the larger monasteries in Gangtok or Pelling, the Linge Phagyal Monastery carries deep religious and cultural significance for the local people. Its age, spiritual heritage, and continuing role in the community make it a notable part of Sikkim’s Buddhist landscape.", 
        hindi: "लिंगे (लिंगी) फग्याल मठ, जिसकी स्थापना 1862 ईस्वी में लामा फग्याल ने की थी, दक्षिण सिक्किम में स्थित एक महत्वपूर्ण बौद्ध मठ है। यह क्षेत्र के प्राचीन मठों में से एक है, जिसे स्थानीय बौद्ध समुदाय की आध्यात्मिक आवश्यकताओं को पूरा करने के उद्देश्य से बनाया गया था। यह मठ तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है और यहाँ पीढ़ी दर पीढ़ी चली आ रही पारंपरिक साधनाएँ, शिक्षाएँ और अनुष्ठान आज भी संरक्षित हैं। दक्षिण सिक्किम की शांत प्राकृतिक सुंदरता से घिरा यह स्थल प्रार्थना और ध्यान के लिए एक अत्यंत उपयुक्त वातावरण प्रदान करता है। यद्यपि यह गंगटोक या पेलिंग के बड़े मठों की तरह व्यापक रूप से प्रसिद्ध नहीं है, फिर भी लिंगे फग्याल मठ स्थानीय लोगों के लिए गहन धार्मिक और सांस्कृतिक महत्व रखता है। इसकी प्राचीनता, आध्यात्मिक विरासत और समुदाय में निभाई जा रही निरंतर भूमिका इसे सिक्किम की बौद्ध परंपरा का एक उल्लेखनीय हिस्सा बनाती है।" }},
  { name: "Karthok Monastery", 
    files: { english: "audios/english/Karthok.mp3",
         hindi: "audios/hindi/Karthok.mp3" }
,
    captions: 
    { english: "The Karthok Monastery, situated in Yuksom, West Sikkim, is regarded as one of the most sacred and historically significant monasteries of the state. Built in the early 18th century by one of the six noble families of Sikkim, it belongs to the Nyingma sect of Tibetan Buddhism, the oldest of all the Buddhist schools. Karthok is especially revered because Yuksom was the first capital of Sikkim and the place where the first Chogyal (king) was crowned in 1642. The monastery was constructed not long after this event to serve as a religious center for the local community and to safeguard the teachings of Buddhism in the region. Perched on a quiet hill, surrounded by forests and overlooking the beautiful Yuksom valley, the monastery exudes an atmosphere of peace and spirituality. Architecturally, it reflects the traditional Tibetan style with brightly painted walls, prayer flags fluttering in the wind, and sacred relics housed inside. The monastery is also associated with several local legends and is believed to be a powerful site of blessings. Every year, festivals and prayer ceremonies are organized here, attracting monks, devotees, and tourists who come to witness the rituals and soak in the cultural experience. The serene environment makes it not only a place of worship but also a retreat for those seeking inner peace. Though not as large as Pemayangtse or Rumtek, Karthok Monastery holds a special place in Sikkim’s spiritual landscape as a reminder of the kingdom’s early history, Buddhist devotion, and cultural identity. Its combination of sacredness, history, and natural beauty continues to make it a significant pilgrimage site as well as a destination for travelers exploring the heritage of Sikkim.", 
        hindi: "कार्थोक मठ, जो पश्चिम सिक्किम के युकसोम में स्थित है, राज्य के सबसे पवित्र और ऐतिहासिक रूप से महत्वपूर्ण मठों में से एक माना जाता है। इसका निर्माण 18वीं शताब्दी की शुरुआत में सिक्किम के छह कुलीन परिवारों में से एक द्वारा किया गया था। यह मठ तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है, जो बौद्ध धर्म की सबसे प्राचीन शाखा है। कार्थोक मठ का विशेष महत्व इसलिए भी है क्योंकि युकसोम सिक्किम की पहली राजधानी थी और यहीं वर्ष 1642 में पहले चोग्याल (राजा) का अभिषेक हुआ था। इसके कुछ समय बाद इस मठ का निर्माण स्थानीय समुदाय के लिए एक धार्मिक केंद्र के रूप में और क्षेत्र में बौद्ध शिक्षाओं की रक्षा हेतु किया गया। यह मठ शांत पहाड़ी पर बसा है, जो जंगलों से घिरा हुआ है और खूबसूरत युकसोम घाटी को निहारता है। इसका वातावरण शांति और आध्यात्मिकता से भरपूर है। स्थापत्य की दृष्टि से यह पारंपरिक तिब्बती शैली को दर्शाता है — रंगीन चित्रित दीवारें, हवा में लहराते प्रार्थना-ध्वज और अंदर सुरक्षित पवित्र अवशेष इसे और भी आकर्षक बनाते हैं। मठ कई स्थानीय किंवदंतियों से भी जुड़ा हुआ है और इसे आशीर्वाद प्रदान करने वाला शक्तिशाली स्थल माना जाता है। प्रत्येक वर्ष यहाँ धार्मिक त्यौहार और प्रार्थना-अनुष्ठान आयोजित किए जाते हैं, जिनमें भिक्षु, श्रद्धालु और पर्यटक बड़ी संख्या में भाग लेते हैं। यहाँ की आध्यात्मिक रस्में और सांस्कृतिक अनुभव इसे विशेष बनाते हैं। हालाँकि यह मठ पेमायंगत्से या रुमटेक जितना बड़ा नहीं है, फिर भी कार्थोक मठ सिक्किम की आध्यात्मिक धरोहर में विशेष स्थान रखता है। यह राज्य के प्रारंभिक इतिहास, बौद्ध भक्ति और सांस्कृतिक पहचान का स्मरण कराता है। पवित्रता, इतिहास और प्राकृतिक सुंदरता का यह अद्वितीय संगम इसे न केवल एक प्रमुख तीर्थस्थल बनाता है बल्कि उन यात्रियों के लिए भी आकर्षण का केंद्र है जो सिक्किम की समृद्ध परंपरा और धरोहर को समझना चाहते हैं।" } },
  { name: "Tsuk La Khang Monastery",
     files: { english: "audios/english/Tsuk.mp3", hindi: "audios/hindi/Tsuk.mp3" } 
,
    captions: { english: "Tsuk La Khang Monastery, also known as Tsuklakhang Royal Chapel and Monastery, is a prominent Buddhist monastery situated in the heart of Gangtok, Sikkim, India. Constructed in 1898 during the reign of the 9th Chogyal, Thutob Namgyal, it served as the royal chapel for the Sikkimese monarchy. The monastery is located within the Tsuklakhang Palace complex, which was the residence of the Chogyals until the monarchy's abolition in 1975. The name Tsuk La Khang translates to Palace Chapel in Tibetan. Architecturally, Tsuk La Khang Monastery exemplifies traditional Tibetan design. The structure is a two-story building adorned with intricately painted murals, statues of various Buddhist deities, and a large collection of Buddhist scriptures. The ground floor houses an assembly hall and altar, while the upper floor contains altars dedicated to tantric deities. The monastery's design reflects the fusion of Tibetan Buddhist architecture with elements unique to Sikkimese culture. Historically, Tsuk La Khang Monastery was the venue for significant royal ceremonies, including coronations and weddings of the Chogyals. It remains a central place of worship for the people of Sikkim and continues to host important Buddhist festivals such as Pang Lhabsol, Kagyad, and Losar. These festivals celebrate the region's rich cultural and spiritual heritage. Today, Tsuk La Khang Monastery stands as a symbol of Sikkim's royal past and its enduring Buddhist traditions. Visitors to Gangtok can explore the monastery to gain insight into the region's history, architecture, and spiritual practices. Its serene atmosphere and historical significance make it a must-visit destination for those interested in the cultural tapestry of Sikkim.",
         hindi: "त्सुक ला खांग मठ, जिसे त्सुकलाखांग रॉयल चैपल एंड मठ भी कहा जाता है, सिक्किम की राजधानी गंगटोक के हृदय में स्थित एक प्रमुख बौद्ध मठ है। इसका निर्माण वर्ष 1898 में सिक्किम के 9वें चोग्याल थुतोब नामग्याल के शासनकाल में किया गया था। यह मठ सikkimese राजशाही का राजकीय चैपल (धार्मिक उपासनागृह) था। यह मठ त्सुकलाखांग पैलेस परिसर के भीतर स्थित है, जो 1975 में राजशाही समाप्त होने तक चोग्यालों का निवास स्थान था। “त्सुक ला खांग” का अर्थ तिब्बती भाषा में पैलेस चैपल यानी महल का उपासनागृह होता है। स्थापत्य की दृष्टि से त्सुक ला खांग मठ पारंपरिक तिब्बती शैली का उत्कृष्ट उदाहरण है। यह दो-मंजिला भवन है, जिसकी दीवारें खूबसूरत भित्ति-चित्रों से सजी हुई हैं। यहाँ विभिन्न बौद्ध देवताओं की मूर्तियाँ और बौद्ध धर्मग्रंथों का विशाल संग्रह मौजूद है। भूतल पर सभा कक्ष और वेदी है, जबकि ऊपरी मंजिल पर तान्त्रिक देवताओं को समर्पित वेदियाँ बनी हुई हैं। इस मठ की रचना तिब्बती बौद्ध स्थापत्य और सिक्किमी संस्कृति के अनूठे मेल को प्रदर्शित करती है। ऐतिहासिक रूप से यह मठ कई महत्वपूर्ण राजकीय अनुष्ठानों का केंद्र रहा है, जिनमें चोग्यालों के राज्याभिषेक और विवाह शामिल थे। आज भी यह सिक्किम के लोगों के लिए आस्था का केंद्र है और यहाँ पांग ल्हाबसोल, कग्याड और लोसर जैसे प्रमुख बौद्ध त्योहार आयोजित किए जाते हैं। ये त्योहार सिक्किम की समृद्ध सांस्कृतिक और आध्यात्मिक धरोहर का उत्सव मनाते हैं।आज त्सुक ला खांग मठ सिक्किम के राजसी अतीत और उसकी स्थायी बौद्ध परंपराओं का प्रतीक है। गंगटोक आने वाले पर्यटक यहाँ आकर न केवल क्षेत्र के इतिहास और स्थापत्य को समझ सकते हैं बल्कि इसके आध्यात्मिक वातावरण का अनुभव भी कर सकते हैं। इसकी शांतिपूर्ण आभा और ऐतिहासिक महत्व इसे सिक्किम की सांस्कृतिक धरोहर में रुचि रखने वाले सभी लोगों के लिए अवश्य देखने योग्य स्थल बनाते हैं।" }},
  { name: "Phensang Monastery",
     files: { english: "audios/english/Phensang.mp3", hindi: "audios/hindi/Phensang.mp3" }
,
    captions: { english: "The Phensang Monastery, located in the northern part of Sikkim, is one of the largest monasteries in the state and an important center of the Nyingma sect of Tibetan Buddhism. Founded in 1721 A.D. during the reign of Jigme Pawo, the third Lhatsun Chenpo, the monastery has been a significant religious and cultural landmark for over three centuries. It is beautifully set on a gentle hill slope, offering panoramic views of the surrounding valleys and mountains, which add to its spiritual atmosphere. The monastery houses around 300 monks, making it not only a place of worship but also a thriving hub of Buddhist learning and community life. Architecturally, it follows the traditional Tibetan style with spacious courtyards, vibrant murals, statues of Buddhist deities, and rows of prayer wheels that reflect the rich cultural heritage of Sikkim. Phensang Monastery is especially known for its annual Cham Festival, held on the 28th and 29th days of the 10th month of the Tibetan lunar calendar, just before the Tibetan New Year (Losar). During this festival, monks perform sacred mask dances accompanied by chants, music, and rituals meant to ward off evil and bring blessings for the year ahead. This colorful and lively celebration attracts large numbers of devotees and tourists from all over the region. Although the monastery was badly damaged by a fire in 1947, it was rebuilt soon after, restoring its former glory and continuing its legacy as a center of faith and culture. Today, the Phensang Monastery remains a symbol of Sikkim’s Buddhist traditions, combining spirituality, history, and community in a setting of natural beauty. Its vibrant monastic life and religious significance make it one of the must-visit monasteries of Sikkim.", 
        hindi: "फेंसांग मठ, सिक्किम के उत्तरी भाग में स्थित, राज्य के सबसे बड़े मठों में से एक है और तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय का महत्वपूर्ण केंद्र माना जाता है। इसकी स्थापना 1721 ईस्वी में जिग्मे पावो, तीसरे ल्हात्सुन चेमपो के शासनकाल में की गई थी। तीन शताब्दियों से यह मठ धार्मिक और सांस्कृतिक दृष्टि से अत्यंत महत्वपूर्ण स्थल रहा है।मठ एक सौम्य पहाड़ी ढलान पर खूबसूरती से स्थित है, जहाँ से चारों ओर घाटियाँ और पर्वत दिखाई देते हैं, जो इसके आध्यात्मिक वातावरण को और भी प्रभावशाली बनाते हैं। मठ में लगभग 300 भिक्षु रहते हैं, जिससे यह केवल उपासना का स्थान नहीं बल्कि बौद्ध अध्ययन और सामुदायिक जीवन का एक जीवंत केंद्र भी है। स्थापत्य की दृष्टि से यह पारंपरिक तिब्बती शैली का अनुसरण करता है, जिसमें विशाल आंगन, जीवंत भित्तिचित्र, बौद्ध देवताओं की मूर्तियाँ और प्रार्थना चक्रों की कतारें शामिल हैं, जो सिक्किम की समृद्ध सांस्कृतिक विरासत को दर्शाती हैं। फेंसांग मठ विशेष रूप से अपने वार्षिक छम महोत्सव (Cham Festival) के लिए जाना जाता है, जो तिब्बती पंचांग के 10वें महीने की 28वीं और 29वीं तिथि को, तिब्बती नववर्ष (लोसर) से ठीक पहले आयोजित होता है। इस दौरान भिक्षु पवित्र मुखौटा नृत्य करते हैं, मंत्रोच्चार, संगीत और अनुष्ठानों के साथ, जो बुराई को दूर करने और आने वाले वर्ष के लिए आशीर्वाद लाने के उद्देश्य से किए जाते हैं। यह रंगीन और जीवंत उत्सव स्थानीय श्रद्धालुओं और पर्यटकों को बड़ी संख्या में आकर्षित करता है। हालाँकि 1947 में मठ आग की घटना से काफी क्षतिग्रस्त हो गया था, इसे शीघ्र ही पुनर्निर्मित किया गया और इसकी भव्यता बहाल की गई। आज, फेंसांग मठ सिक्किम की बौद्ध परंपराओं का प्रतीक बना हुआ है, जो प्राकृतिक सुंदरता के बीच आध्यात्मिकता, इतिहास और सामुदायिक जीवन का अद्भुत संगम प्रस्तुत करता है। यहाँ का जीवंत मठ जीवन और धार्मिक महत्व इसे सिक्किम के अवश्य देखने योग्य मठों में से एक बनाते हैं।" } },
  { name: "Phodong Monastery",
     files: { english: "audios/english/Phodong.mp3", hindi: "audios/hindi/Phodong.mp3" } 
,
    captions:
     { english: "The Phodong Monastery, located about 28 kilometers from Gangtok in North Sikkim, is one of the most important monasteries belonging to the Kagyu sect of Tibetan Buddhism. Originally built in the early 18th century under the patronage of the Chogyal Gyurmed Namgyal, it stands as a significant symbol of Sikkim’s Buddhist heritage. Although the original structure fell into ruins, a new monastery was constructed in the early 20th century, which continues to flourish today. The monastery is renowned for its beautiful architecture, decorated walls, vibrant murals, and an impressive collection of Buddhist scriptures and paintings that illustrate the spiritual richness of Tibetan Buddhism. Home to around 250 monks, Phodong Monastery is not only a religious center but also a place of monastic education and practice. The serene location, surrounded by wooded hills and overlooking valleys, creates an atmosphere of peace and devotion that attracts both pilgrims and tourists. One of the highlights of the monastery is the annual Chaam Festival, where monks perform sacred mask dances accompanied by chanting and traditional music. This colorful event, held in December, draws large crowds who come to witness the spiritual and cultural spectacle, which is believed to drive away evil spirits and bring prosperity. Apart from its religious importance, Phodong is also linked to the history of Buddhism in Sikkim, as it was one of the three important monasteries (along with Rumtek and Ralang) established under royal patronage. Its role in preserving the teachings, rituals, and cultural traditions of the Kagyu sect has made it a cornerstone of Sikkim’s spiritual life. Today, Phodong Monastery continues to serve as a place of prayer, learning, and cultural preservation, standing proudly as a testament to the enduring Buddhist faith in the region.",
         hindi: "फोडोंग मठ, उत्तर सिक्किम में गंगटोक से लगभग 28 किलोमीटर दूर स्थित, तिब्बती बौद्ध धर्म के काग्यु सम्प्रदाय का एक अत्यंत महत्वपूर्ण मठ है। इसकी स्थापना 18वीं शताब्दी की शुरुआत में सिक्किम के चोग्याल ग्युरमेद नामग्याल के संरक्षण में की गई थी और यह सिक्किम की बौद्ध धरोहर का एक महत्वपूर्ण प्रतीक माना जाता है। हालांकि मूल संरचना खंडहर में परिवर्तित हो गई थी, 20वीं शताब्दी की शुरुआत में इसका नया मठ बनाया गया, जो आज भी प्रगतिशील रूप से फल-फूल रहा है। मठ अपनी सुंदर वास्तुकला, सजाई गई दीवारों, जीवंत भित्तिचित्रों और बौद्ध धर्मग्रंथों और चित्रों के प्रभावशाली संग्रह के लिए प्रसिद्ध है, जो तिब्बती बौद्ध धर्म की आध्यात्मिक समृद्धि को दर्शाते हैं। यहाँ लगभग 250 भिक्षु रहते हैं, जिससे फोडोंग मठ केवल एक धार्मिक केंद्र नहीं बल्कि मठीय शिक्षा और साधना का भी केंद्र है। शांतिपूर्ण स्थान, चारों ओर जंगलों से घिरा और घाटियों को निहारता हुआ, यहाँ का वातावरण भक्ति और शांति से भरपूर है, जो श्रद्धालुओं और पर्यटकों दोनों को आकर्षित करता है। मठ की प्रमुख विशेषताओं में वार्षिक छम महोत्सव (Chaam Festival) शामिल है, जिसमें भिक्षु पवित्र मुखौटा नृत्य करते हैं, मंत्रोच्चार और पारंपरिक संगीत के साथ। यह रंगीन उत्सव दिसंबर में आयोजित होता है और बड़ी संख्या में दर्शकों को आकर्षित करता है। इसे बुरी आत्माओं को दूर करने और समृद्धि लाने वाला माना जाता है।धार्मिक महत्व के अलावा, फोडोंग मठ सिक्किम में बौद्ध धर्म के इतिहास से भी जुड़ा हुआ है, क्योंकि यह रुमटेक और रालोंग के साथ मिलकर तीन प्रमुख मठों में से एक था, जिसे राजकीय संरक्षण में स्थापित किया गया था। काग्यु सम्प्रदाय की शिक्षाओं, अनुष्ठानों और सांस्कृतिक परंपराओं को संरक्षित करने में इसका योगदान सिक्किम के आध्यात्मिक जीवन का एक स्तंभ बनाता है।आज भी, फोडोंग मठ प्रार्थना, शिक्षा और सांस्कृतिक संरक्षण का स्थान बना हुआ है, और यह क्षेत्र में बौद्ध धर्म की स्थायी आस्था का एक गर्वपूर्ण प्रतीक है।" }},
  { name: "Labrong Monastery", 
    files: { english: "audios/english/Labrong.mp3", hindi: "audios/hindi/Labrong.mp3" }
,
    captions: { english: "The Labrang Monastery, also known locally as Labrong Monastery, is a significant Buddhist monastery located near Phodong in North Sikkim. Belonging to the Kagyu sect of Tibetan Buddhism, it was established in the early 19th century by Gyurmed Namgyal, one of the rulers of Sikkim, and is closely connected with the history of the nearby Phodong Monastery. The word “Labrang” means “residence of the lamas,” and true to its name, the monastery has long served as a spiritual home for Buddhist monks dedicated to prayer, meditation, and learning. Architecturally, the monastery reflects traditional Tibetan design, with intricately painted walls, vibrant murals, and statues of Buddhist deities that create a serene and sacred atmosphere. Surrounded by lush hillsides and valleys, it offers a peaceful retreat for devotees and visitors alike. Like other important monasteries of Sikkim, Labrang is known for its annual religious festivals, especially the Chaam dances, where monks perform masked dances accompanied by ritual chants and traditional music. These sacred performances are believed to drive away negative forces and usher in peace, prosperity, and spiritual purification. Though not as large or as famous as Rumtek or Pemayangtse, Labrang Monastery holds deep cultural and religious value, especially for the local community that has preserved its traditions for centuries. It also forms part of the trio of significant Kagyu monasteries in the region, along with Phodong and Ralang, each contributing to the continuation of Buddhist teachings in Sikkim. Today, the monastery remains a center for monastic education, religious practice, and community festivals, drawing both pilgrims and curious travelers who seek to experience Sikkim’s spiritual heritage. With its combination of natural beauty, historical roots, and religious importance, the Labrang Monastery stands as a testament to Sikkim’s enduring Buddhist culture.", 
        hindi: "लाब्रांग मठ, जिसे स्थानीय रूप से लाब्रॉन्ग मठ भी कहा जाता है, उत्तर सिक्किम के फोडोंग के पास स्थित एक महत्वपूर्ण बौद्ध मठ है। यह तिब्बती बौद्ध धर्म के काग्यु सम्प्रदाय से संबंधित है। इसकी स्थापना 19वीं शताब्दी की शुरुआत में सिक्किम के शासक ग्युरमेद नामग्याल द्वारा की गई थी और यह पास ही स्थित फोडोंग मठ के इतिहास से गहराई से जुड़ा हुआ है। “लाब्रांग” का अर्थ है लामा निवास स्थान। अपने नाम के अनुरूप, यह मठ लंबे समय से भिक्षुओं के लिए एक आध्यात्मिक घर रहा है, जहाँ वे प्रार्थना, ध्यान और अध्ययन में संलग्न रहते हैं। स्थापत्य की दृष्टि से यह मठ पारंपरिक तिब्बती शैली को दर्शाता है, जिसमें जटिल चित्रकारी वाली दीवारें, जीवंत भित्तिचित्र और बौद्ध देवताओं की मूर्तियाँ शामिल हैं, जो वातावरण को शांति और पवित्रता से भर देती हैं। घने हरे-भरे पहाड़ी ढलानों और घाटियों से घिरा यह मठ श्रद्धालुओं और पर्यटकों दोनों के लिए शांतिपूर्ण स्थल प्रदान करता है। सिक्किम के अन्य प्रमुख मठों की तरह, लाब्रांग मठ अपने वार्षिक धार्मिक त्योहारों के लिए भी प्रसिद्ध है, विशेषकर छम नृत्य (Chaam dances) के लिए, जिसमें भिक्षु मुखौटा पहनकर नृत्य करते हैं, मंत्रोच्चार और पारंपरिक संगीत के साथ। इन पवित्र प्रदर्शनों को नकारात्मक शक्तियों को दूर करने और शांति, समृद्धि तथा आध्यात्मिक शुद्धि लाने वाला माना जाता है। हालाँकि यह रुमटेक या पेमायंगत्से जितना बड़ा या प्रसिद्ध नहीं है, फिर भी लाब्रांग मठ सांस्कृतिक और धार्मिक दृष्टि से अत्यंत महत्वपूर्ण है, खासकर स्थानीय समुदाय के लिए जिन्होंने इसकी परंपराओं को सदियों तक संरक्षित किया है। यह क्षेत्र के तीन प्रमुख काग्यु मठों (फोडोंग, रालोंग और लाब्रांग) में से एक है, जो सिक्किम में बौद्ध शिक्षाओं की निरंतरता में योगदान देते हैं। आज भी, लाब्रांग मठ मठीय शिक्षा, धार्मिक साधना और सामुदायिक त्योहारों का केंद्र बना हुआ है, और यह तीर्थयात्रियों और पर्यटकों दोनों को आकर्षित करता है जो सिक्किम की आध्यात्मिक धरोहर का अनुभव करना चाहते हैं। प्राकृतिक सुंदरता, ऐतिहासिक महत्व और धार्मिक मूल्य के संयोजन के कारण, लाब्रांग मठ सिक्किम की स्थायी बौद्ध संस्कृति का एक जीवंत प्रमाण है।" } },
  { name: "Tholung Monastery", 
    files: { english: "audios/english/Tolung.mp3", hindi: "audios/hindi/Tolung.mp3" }
,
    captions: { english: "Tholung Monastery, located in the remote upper reaches of Dzongu in North Sikkim, is one of the most sacred and historically significant Buddhist monasteries in the region. Established in 1789 by Lhatsun Pema Dechhen Gyatso, the monastery was constructed to house invaluable spiritual artifacts and relics brought from other monasteries for safekeeping during the Nepalese invasions of the late 17th and early 19th centuries. These relics include ancient manuscripts, sacred texts, and a metal chorten containing the ashes of Lama Latsun Chembo, the revered patron saint of Sikkim. The monastery follows the Nyingma school of Tibetan Buddhism and is situated within the buffer zone of the Khangchendzonga National Park, a UNESCO World Heritage Site. Due to the region's cold and moist climate, the relics are preserved in sealed boxes and are unveiled to the public every three years during the Kamsil Ceremony held in April. This rare event attracts devotees and tourists alike, who come to witness the sacred relics and partake in the spiritual atmosphere. The journey to Tholung Monastery is a pilgrimage in itself, requiring a challenging trek through dense forests and rugged terrain, reflecting the monastery's secluded and revered status. Tholung Monastery is not only a center of spiritual learning and practice but also a symbol of the resilience and devotion of the people of Sikkim. Its rich history, cultural significance, and the breathtaking natural beauty surrounding it make it a must-visit destination for those seeking to understand the deep-rooted Buddhist traditions of the region.",
         hindi: "थोलुंग मठ, उत्तर सिक्किम के दूरदराज़ डज़ोंगु क्षेत्र की ऊपरी घाटियों में स्थित, क्षेत्र के सबसे पवित्र और ऐतिहासिक रूप से महत्वपूर्ण बौद्ध मठों में से एक है। इसकी स्थापना 1789 में ल्हात्सुन पेमा डेछेन ग्यात्सो द्वारा की गई थी। इस मठ का निर्माण अन्य मठों से लाए गए अनमोल आध्यात्मिक अवशेषों और पवित्र relics को सुरक्षित रखने के लिए किया गया था, खासकर नेपाली आक्रमणों के दौरान 17वीं और 19वीं शताब्दी के बीच। इन अवशेषों में प्राचीन पांडुलिपियाँ, पवित्र ग्रंथ और एक धातु चोर्तेन शामिल हैं, जिसमें सिक्किम के प्रतिष्ठित संरक्षक संत लामा ल्हात्सुन चेम्पो की राख रखी गई है। मठ तिब्बती बौद्ध धर्म के निंगमा स्कूल से संबंधित है और यह खंगचेंदजोंगा राष्ट्रीय उद्यान (UNESCO विश्व धरोहर स्थल) के बफर क्षेत्र में स्थित है। क्षेत्र के ठंडे और आर्द्र जलवायु के कारण, ये अवशेष सीलबंद बक्सों में संरक्षित किए गए हैं और हर तीन साल में कांसिल समारोह (Kamsil Ceremony) के दौरान अप्रैल में जनता के सामने प्रदर्शित किए जाते हैं। यह दुर्लभ अवसर श्रद्धालुओं और पर्यटकों दोनों को आकर्षित करता है, जो पवित्र relics को देखने और आध्यात्मिक वातावरण का अनुभव करने आते हैं। थोलुंग मठ तक पहुँचने की यात्रा स्वयं एक तीर्थयात्रा है, जिसमें घने जंगलों और कठिन भू-भाग से होकर लंबा पैदल मार्ग तय करना पड़ता है, जो मठ की दूरस्थ और प्रतिष्ठित स्थिति को दर्शाता है।  थोलुंग मठ केवल आध्यात्मिक अध्ययन और साधना का केंद्र नहीं है, बल्कि यह सिक्किम के लोगों की श्रद्धा और दृढ़ता का प्रतीक भी है। इसकी समृद्ध ऐतिहासिक विरासत, सांस्कृतिक महत्व और आसपास की अद्भुत प्राकृतिक सुंदरता इसे उन लोगों के लिए अवश्य देखने योग्य स्थल बनाती है, जो इस क्षेत्र की गहरी बौद्ध परंपराओं को समझना चाहते हैं।।" } },
  { name: "Bermoik Monastery", 
    files: { english: "audios/english/Bermoik.mp3", hindi: "audios/hindi/Bermoik.mp3" }
,
    captions: 
    { english: "The Bermiok Monastery, also known as Bermiok Wosel Choling Gonpa, is a significant Buddhist monastery located in South Sikkim, northeastern India. Established in 1873, it belongs to the Karma Kagyu lineage of Tibetan Buddhism The monastery was founded through the collective efforts of local lamas and laypeople  Over the years, it has undergone renovations, notably in 1954 and 1987, to preserve its structure and spiritual significance. A notable feature within the monastery complex is the Thangshing Bermiok Manilakhang, a small one-story structure housing statues of Amitābha and the Chag-tong Chentong form of Avalokiteśvara. The Manilakhang is surrounded by Mani wheels, which are traditional prayer wheels used in Tibetan Buddhism. An old Mani wheel within the structure is believed to produce omens through its spinning and the sounds it emits, serving as a spiritual indicator for the local community The monastery's serene location offers panoramic views of the surrounding landscapes, making it a peaceful retreat for meditation and spiritual practice. It also serves as a cultural hub, reflecting the rich Buddhist heritage of Sikkim. For those interested in exploring the spiritual and cultural tapestry of Sikkim, the Bermiok Monastery stands as a testament to the region's deep-rooted Buddhist traditions and community efforts in preserving them.",
         hindi: "बर्मीओक मठ, जिसे बर्मीओक वोसेल चोलिंग गोंपा भी कहा जाता है, दक्षिण सिक्किम, भारत के उत्तर-पूर्वी भाग में स्थित एक महत्वपूर्ण बौद्ध मठ है। इसकी स्थापना 1873 में हुई थी और यह तिब्बती बौद्ध धर्म के कर्मा काग्यु संप्रदाय से संबंधित है।इस मठ की स्थापना स्थानीय लामा और आम लोगों के सामूहिक प्रयासों से हुई थी। वर्षों के दौरान, मठ की संरचना और आध्यात्मिक महत्व को संरक्षित रखने के लिए इसे कई बार नवीनीकृत किया गया, विशेष रूप से 1954 और 1987 में। मठ परिसर की एक प्रमुख विशेषता है थांगशिंग बर्मीओक मणिलाखांग, एक छोटा एक-मंजिला ढांचा जिसमें अमिताभ और चैग-टोंग चेंटोंग रूप के अवलोकितेश्वर की मूर्तियाँ स्थित हैं। मणिलाखांग के चारों ओर मणि चक्र हैं, जो तिब्बती बौद्ध धर्म में पारंपरिक प्रार्थना चक्रों के रूप में उपयोग किए जाते हैं। संरचना के भीतर एक पुराना मणि चक्र माना जाता है कि इसके घूमने और उत्पन्न होने वाली ध्वनि के माध्यम से शुभ या अशुभ संकेत देता है, जो स्थानीय समुदाय के लिए आध्यात्मिक मार्गदर्शन का कार्य करता है। मठ का शांतिपूर्ण स्थान आसपास के दृश्यों का मनोरम दृश्य प्रस्तुत करता है, जिससे यह ध्यान और आध्यात्मिक साधना के लिए एक आदर्श स्थल बन जाता है। यह सांस्कृतिक केंद्र के रूप में भी कार्य करता है, जो सिक्किम की समृद्ध बौद्ध विरासत को दर्शाता है। सिक्किम की आध्यात्मिक और सांस्कृतिक धरोहर को जानने वाले पर्यटकों के लिए, बर्मीओक मठ क्षेत्र की गहरी बौद्ध परंपराओं और इन्हें संरक्षित करने में स्थानीय समुदाय के प्रयासों का एक महत्वपूर्ण प्रमाण है।" } },
  { name: "Dolling Monastery",
     files: { english: "audios/english/Dolling.mp3", hindi: "audios/hindi/Dolling.mp3" } 
,
    captions:
     { english: "The Doling Monastery, also known as Doling Gonpa, is a revered Buddhist monastery situated approximately 6 kilometers south of Ravangla in South Sikkim, India. Founded in 1718 AD by Lama Rigdzin Longyang, the monastery belongs to the Nyingma sect of Tibetan Buddhism and holds significant cultural and spiritual importance in the region.The monastery's establishment is intertwined with the historical migration of Lama Dorjelingpa and his son Rigdzin Longyang from Tibet during the Mongol ruler Junggar's invasion in 1717–1718 AD. They sought refuge in Sikkim and constructed the Doling Monastery as a sanctuary for Buddhist teachings and practices.Over the centuries, Doling Monastery has undergone several reconstructions due to earthquake damages, with notable rebuilding efforts in 1840, 1920, and 1984. Despite these challenges, the monastery has preserved its spiritual essence and continues to serve as a center for meditation, prayer, and monastic education. A distinctive feature of Doling Monastery is the footprint of Khangchendzonga's horse and that of Lama Dorjelingpa, believed to be imprinted on a rock near the monastery. According to local legend, during the consecration ceremony of the monastery, Khangchendzonga arrived late and left the footprint as a sign of his presence. Lama Dorjelingpa responded by leaving his own footprint, symbolizing mutual respect and understanding between the deity and the lama.Today, Doling Monastery remains a serene and sacred site, attracting pilgrims and visitors seeking spiritual solace and a glimpse into the rich Buddhist heritage of Sikkim. Its tranquil setting amidst lush greenery and panoramic views of the Himalayas further enhances its appeal as a destination for reflection and cultural exploration.",
         hindi: "डोलिंग मठ, जिसे डोलिंग गोंपा भी कहा जाता है, दक्षिण सिक्किम, भारत में रावांगला से लगभग 6 किलोमीटर दक्षिण स्थित एक पवित्र बौद्ध मठ है। इसकी स्थापना 1718 ईस्वी में लामा रिग्द्ज़िन लोंगयांग द्वारा की गई थी। यह मठ तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है और क्षेत्र में सांस्कृतिक तथा आध्यात्मिक दृष्टि से अत्यंत महत्वपूर्ण माना जाता है।मठ की स्थापना लामा डोरजेलिंगपा और उनके पुत्र रिग्द्ज़िन लोंगयांग के तिब्बत से सिक्किम के लिए पलायन के साथ जुड़ी हुई है। यह पलायन 1717–1718 ईस्वी में मंगोल शासक जुंग्गार के आक्रमण के दौरान हुआ। उन्होंने सिक्किम में शरण ली और बौद्ध शिक्षाओं और साधना के लिए डोलिंग मठ का निर्माण किया। सदियों के दौरान, डोलिंग मठ कई बार भूकंप से क्षतिग्रस्त होने के कारण पुनर्निर्मित किया गया, जिसमें प्रमुख नवीनीकरण कार्य 1840, 1920 और 1984 में हुए। इन चुनौतियों के बावजूद, मठ ने अपनी आध्यात्मिक महत्ता बनाए रखी और यह आज भी ध्यान, प्रार्थना और मठीय शिक्षा का केंद्र है। डोलिंग मठ की एक विशिष्ट विशेषता है खंगचेंदजोंगा के घोड़े के पदचिह्न और लामा डोरजेलिंगपा का पदचिह्न, जो मठ के पास एक चट्टान पर अंकित माने जाते हैं। स्थानीय किंवदंती के अनुसार, मठ के उद्घाटन समारोह के दौरान खंगचेंदजोंगा देर से आए और अपनी उपस्थिति का संकेत देने के लिए पदचिह्न छोड़ा। इसके उत्तर में लामा डोरजेलिंगपा ने अपना पदचिह्न छोड़ा, जो देवता और लामा के बीच परस्पर सम्मान और समझ का प्रतीक माना जाता है।आज, डोलिंग मठ एक शांत और पवित्र स्थल के रूप में मौजूद है, जो श्रद्धालुओं और पर्यटकों को आध्यात्मिक शांति और सिक्किम की समृद्ध बौद्ध विरासत का अनुभव प्रदान करता है। चारों ओर हरी-भरी घाटियाँ और हिमालय के मनोरम दृश्य इसे विचार, ध्यान और सांस्कृतिक अन्वेषण के लिए एक आकर्षक गंतव्य बनाते हैं।" }},
  { name: "Yangyang Monastery", 
    files: { english: "audios/english/Yangyang.mp3", 
        hindi: "audios/hindi/Yangyang.mp3" } 
,
    captions:
     { english: "The **Yangyang Monastery**, also known as **Yangyang Wosel Choeling**, is a significant Buddhist monastery located in the southern part of Sikkim, India. Situated approximately 10 kilometers downhill from Ravangla, it was established in **1840** and follows the **Nyingma** sect of Tibetan Buddhism The monastery's name, Yangyang, translates to the ridge of fortune, reflecting its auspicious location amidst the serene landscapes of Sikkim. Over the years, Yangyang Monastery has undergone several reconstructions due to natural calamities, notably in **1954** and **1987**, to preserve its spiritual and architectural heritage . A distinctive feature of the monastery is the **Thangshing Bermiok Manilakhang**, a small one-story structure housing statues of **Amitābha** and the **Chag-tong Chentong** form of **Avalokiteśvara**. The Manilakhang is surrounded by Mani wheels, traditional prayer wheels used in Tibetan Buddhism. An old Mani wheel within the structure is believed to produce omens through its spinning and the sounds it emits, serving as a spiritual indicator for the local community. The monastery's serene location offers panoramic views of the surrounding landscapes, making it a peaceful retreat for meditation and spiritual practice. It also serves as a cultural hub, reflecting the rich Buddhist heritage of Sikkim. For those interested in exploring the spiritual and cultural tapestry of Sikkim, the Yangyang Monastery stands as a testament to the region's deep-rooted Buddhist traditions and community efforts in preserving them.", 
        hindi: "यांगयांग मठ, जिसे यांगयांग वोसेल चोलिंग भी कहा जाता है, भारत के सिक्किम के दक्षिणी भाग में स्थित एक महत्वपूर्ण बौद्ध मठ है। यह रावांगला से लगभग 10 किलोमीटर नीचे स्थित है और तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है। मठ का नाम यांगयांग का अर्थ है सौभाग्य की चोटी, जो सिक्किम के शांतिपूर्ण प्राकृतिक परिदृश्यों के बीच इसकी शुभ स्थिति को दर्शाता है। समय के साथ, यांगयांग मठ ने प्राकृतिक आपदाओं के कारण कई बार पुनर्निर्माण किया है, विशेष रूप से 1954 और 1987 में, ताकि इसकी आध्यात्मिक और स्थापत्य विरासत सुरक्षित रहे। मठ की एक विशिष्ट विशेषता है थांगशिंग बर्मीओक मणिलाखांग, एक छोटा एक-मंजिला ढांचा जिसमें अमिताभ और अवलोकितेश्वर के चैग-टोंग चेंटोंग रूप की मूर्तियाँ स्थित हैं। मणिलाखांग के चारों ओर मणि चक्र लगे हैं, जो तिब्बती बौद्ध धर्म में पारंपरिक प्रार्थना चक्रों के रूप में उपयोग किए जाते हैं। संरचना के भीतर एक पुराना मणि चक्र ऐसा माना जाता है कि इसके घूमने और उत्पन्न होने वाली ध्वनि के माध्यम से शुभ या अशुभ संकेत देता है, जो स्थानीय समुदाय के लिए आध्यात्मिक मार्गदर्शन का कार्य करता है। मठ का शांतिपूर्ण स्थान आसपास के दृश्यों का मनोरम दृश्य प्रस्तुत करता है, जिससे यह ध्यान और आध्यात्मिक साधना के लिए एक आदर्श स्थल बन जाता है। यह सांस्कृतिक केंद्र के रूप में भी कार्य करता है, जो सिक्किम की समृद्ध बौद्ध विरासत को दर्शाता है। सिक्किम की आध्यात्मिक और सांस्कृतिक धरोहर को जानने वाले पर्यटकों के लिए, यांगयांग मठ क्षेत्र की गहरी बौद्ध परंपराओं और इन्हें संरक्षित करने में स्थानीय समुदाय के प्रयासों का एक महत्वपूर्ण प्रमाण है।" }},
  { name: "Namchi Monastery", 
    files: { english: "audios/english/Namchi.mp3", 
        hindi: "audios/hindi/Namchi.mp3" }
,
    captions: { english: "Namchi Monastery, also known as Ngadak Monastery, is one of the oldest and most revered Buddhist monasteries in South Sikkim, India. Situated approximately 4 kilometers from the Namchi town center, it offers panoramic views of the surrounding landscapes. The monastery was established in 1700 by Chogyal Gyurmed Namgyal, the then ruler of Sikkim, and is affiliated with the Nyingma sect of Tibetan Buddhism. The monastery's architecture is a testament to traditional Tibetan design, featuring intricately painted walls, vibrant murals, and statues of various Buddhist deities. These artistic elements not only enhance the spiritual ambiance but also serve as visual narratives of Buddhist teachings and legends.One of the monastery's significant features is its association with the Samdruptse Hill, located nearby. The hill is home to a towering statue of Guru Padmasambhava, also known as Guru Rinpoche, who is considered the patron saint of Sikkim. This 135-foot-tall statue is a prominent landmark and a symbol of spiritual significance for the region. Throughout the year, Namchi Monastery hosts various Buddhist festivals and rituals, attracting devotees and tourists alike. These events provide insight into the rich cultural and spiritual heritage of Sikkim. The serene environment, coupled with the monastery's historical and spiritual importance, makes it a must-visit destination for those seeking to experience the profound Buddhist traditions of the region.",
         hindi: "नामची मठ, जिसे ङ्गदक मठ भी कहा जाता है, भारत के सिक्किम के दक्षिण हिस्से में स्थित सबसे पुराने और सम्मानित बौद्ध मठों में से एक है। यह मठ नामची शहर के केंद्र से लगभग 4 किलोमीटर दूर स्थित है और आसपास के मनोरम दृश्यों का अद्भुत दृश्य प्रदान करता है।मठ की स्थापना 1700 में सिक्किम के तत्कालीन शासक चोग्याल गुरमेद नमग्याल द्वारा की गई थी और यह तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है। मठ की वास्तुकला पारंपरिक तिब्बती डिज़ाइन का उत्कृष्ट उदाहरण है, जिसमें बारीक चित्रित दीवारें, जीवंत भित्ति चित्र (म्यूरल्स), और विभिन्न बौद्ध देवी-देवताओं की मूर्तियाँ शामिल हैं। ये कलात्मक तत्व न केवल आध्यात्मिक वातावरण को बढ़ाते हैं, बल्कि बौद्ध शिक्षाओं और कथाओं की दृश्य व्याख्या भी प्रदान करते हैं।मठ की एक विशेष पहचान इसका सामद्रुप्त्से हिल से संबंध है, जो पास ही स्थित है। इस पहाड़ी पर गुरु पद्मसंभव, जिन्हें गुरु रिनपोचे भी कहा जाता है, की एक विशाल 135 फीट ऊँची मूर्ति स्थित है। गुरु पद्मसंभव को सिक्किम का संरक्षक संत माना जाता है। यह मूर्ति क्षेत्र का एक प्रमुख स्थलचिह्न और आध्यात्मिक प्रतीक है। साल भर, नामची मठ विभिन्न बौद्ध त्योहारों और अनुष्ठानों की मेजबानी करता है, जो श्रद्धालुओं और पर्यटकों को आकर्षित करते हैं। ये आयोजन सिक्किम की समृद्ध सांस्कृतिक और आध्यात्मिक विरासत की झलक प्रदान करते हैं।मठ का शांत वातावरण, इसके ऐतिहासिक और आध्यात्मिक महत्व के साथ मिलकर इसे उन लोगों के लिए एक अनिवार्य गंतव्य बनाता है, जो क्षेत्र की गहन बौद्ध परंपराओं का अनुभव करना चाहते हैं।" } },
  { name: "Rinchenpong Monastery",
     files: { english: "audios/english/Rinchenpong.mp3", hindi: "audios/hindi/Rinchenpong.mp3" }
,
    captions:
     { english: "Rinchenpong Monastery, also known as Sang Ngag Yangtse Monastery, is a significant Buddhist monastery situated in the village of Rinchenpong in West Sikkim, India. Established in 1730 by Ngadakpa Lama, it stands as the third oldest monastery in Sikkim, following Pemayangtse and Phodong .The monastery is renowned for housing a rare Ati Buddha (Adi-Buddha) statue in the Yab-Yum position, symbolizing the union of wisdom and compassion. This unique representation is a significant feature of the monastery.Visitors can reach the monastery by a scenic trail from Rinchenpong village, passing through lush maize fields and ascending a series of stone steps. The journey culminates at the monastery, offering panoramic views of the surrounding landscapes.Today, Rinchenpong Monastery continues to serve as a center for Buddhist teachings and practices, attracting pilgrims and tourists alike who seek spiritual solace and a deeper understanding of Sikkim's rich cultural heritage.",
         hindi: "रिंचेनपोंग मठ, जिसे सांग नाग यांग्त्से मठ भी कहा जाता है, भारत के पश्चिमी सिक्किम के रिंचेनपोंग गाँव में स्थित एक महत्वपूर्ण बौद्ध मठ है। इसकी स्थापना 1730 में नगडकपा लामा द्वारा की गई थी और यह सिक्किम का तीसरा सबसे पुराना मठ है, पेमायांगत्से और फोदोंग के बाद।मठ विशेष रूप से एक दुर्लभ अति बुद्ध (आदि-बुद्ध) की मूर्ति के लिए प्रसिद्ध है, जो याब-युम मुद्रा में स्थित है। यह मुद्रा ज्ञान और करुणा के संघ का प्रतीक है और मठ की सबसे विशिष्ट विशेषताओं में से एक है।पर्यटक मठ तक पहुँचने के लिए रिंचेनपोंग गाँव से एक सौंदर्यपूर्ण मार्ग तय करते हैं, जो हरे-भरे मक्का के खेतों से होकर जाता है और पत्थर की सीढ़ियों की श्रृंखला पर चढ़ता है। यात्रा के अंत में, मठ से आसपास के प्राकृतिक दृश्यों का मनोरम दृश्य दिखाई देता है।आज, रिंचेनपोंग मठ बौद्ध शिक्षाओं और साधनाओं का केंद्र बने हुए है, जो श्रद्धालुओं और पर्यटकों को आध्यात्मिक शांति और सिक्किम की समृद्ध सांस्कृतिक विरासत की गहरी समझ प्रदान करता है।" } },
  { name: "Tingbung Monastery",
     files: { english: "audios/english/Tingbung.mp3", hindi: "audios/hindi/Tingbung.mp3" }
,
    captions: 
    { english: "Tingbung Monastery is a relatively lesser-known yet culturally significant monastery located in North Sikkim, about 85 kilometers from Gangtok. Unlike some of the more famous monasteries in the state, Tingbung stands out for its serene setting and deep-rooted connection to the local community. Established to serve the spiritual needs of the villagers, the monastery belongs to the Nyingma sect of Tibetan Buddhism, one of the oldest Buddhist traditions. Its construction reflects the devotion of the local people, who actively participate in maintaining the monastery and preserving its teachings. Tingbung Monastery is modest in scale compared to larger centers like Rumtek or Pemayangtse, but it holds great importance as a focal point of faith, culture, and social life for the nearby villages. The architecture of the monastery follows traditional Sikkimese and Tibetan styles, with brightly painted walls, prayer flags fluttering in the mountain breeze, and images of Buddhist deities inside the main hall. The prayer hall is adorned with murals, thangkas, and sacred scriptures that narrate Buddhist philosophy and legends. Monks and villagers regularly gather here for prayers, meditation, and rituals that strengthen the spiritual fabric of the community. One of the highlights of Tingbung is its vibrant annual festival, where masked Cham dances are performed by monks to symbolize the triumph of good over evil and to invoke blessings for peace and prosperity. Beyond its spiritual role, Tingbung Monastery also serves as a center for cultural preservation. The younger generation of monks is trained in Buddhist scriptures, rituals, and traditional practices, ensuring the continuity of Sikkim’s heritage. Surrounded by the natural beauty of North Sikkim’s hills and forests, the monastery provides a sense of tranquility and retreat for both residents and visitors. Though less explored by tourists, Tingbung Monastery represents the essence of Sikkim’s Buddhist identity—a harmonious blend of devotion, culture, and nature.",
         hindi: "टिंगबुंग मठ उत्तर सिक्किम में स्थित एक अपेक्षाकृत कम प्रसिद्ध लेकिन सांस्कृतिक रूप से महत्वपूर्ण बौद्ध मठ है, जो गंगटोक से लगभग 85 किलोमीटर दूर है। राज्य के कुछ प्रसिद्ध मठों के विपरीत, टिंगबुंग अपने शांत वातावरण और स्थानीय समुदाय के साथ गहरे जुड़ाव के लिए जाना जाता है।मठ की स्थापना गाँव वालों की आध्यात्मिक आवश्यकताओं की पूर्ति के लिए की गई थी और यह तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है, जो सबसे प्राचीन बौद्ध परंपराओं में से एक है। इसका निर्माण स्थानीय लोगों की भक्ति और सहयोग को दर्शाता है, जो मठ के रखरखाव और शिक्षाओं के संरक्षण में सक्रिय रूप से भाग लेते हैं।टिंगबुंग मठ आकार में रुमटेक या पेमायांगत्से जैसे बड़े केंद्रों की तुलना में छोटा है, लेकिन यह आसपास के गाँवों के लिए विश्वास, संस्कृति और सामाजिक जीवन का एक महत्वपूर्ण केंद्र है। मठ की वास्तुकला पारंपरिक सिक्किमी और तिब्बती शैली का अनुसरण करती है, जिसमें चमकीले रंग की दीवारें, पर्वतीय हवा में लहराते प्रार्थना झंडे और मुख्य हॉल के अंदर बौद्ध देवताओं की छवियाँ शामिल हैं। प्रार्थना हॉल में भित्ति चित्र, थांग्का और पवित्र ग्रंथ हैं, जो बौद्ध दर्शन और कथाओं का वर्णन करते हैं।यहाँ के भिक्षु और गाँव वाले नियमित रूप से प्रार्थना, ध्यान और अनुष्ठानों के लिए इकट्ठा होते हैं, जो समुदाय की आध्यात्मिक संस्कृति को मजबूत बनाते हैं। टिंगबुंग का एक प्रमुख आकर्षण इसका सालाना उत्सव है, जिसमें भिक्षु मास्कधारी चाम नृत्य प्रस्तुत करते हैं, जो बुराई पर अच्छाई की विजय और शांति व समृद्धि की प्रार्थना का प्रतीक है।आध्यात्मिक भूमिका के अलावा, टिंगबुंग मठ सांस्कृतिक संरक्षण का केंद्र भी है। यहाँ युवा भिक्षुओं को बौद्ध ग्रंथों, अनुष्ठानों और पारंपरिक प्रथाओं में प्रशिक्षण दिया जाता है, जिससे सिक्किम की विरासत की निरंतरता बनी रहती है। उत्तर सिक्किम की पहाड़ियों और जंगलों की प्राकृतिक सुंदरता से घिरा यह मठ स्थानीय लोगों और पर्यटकों दोनों के लिए शांति और ध्यान का स्थान प्रदान करता है।कम पर्यटक आकर्षण के बावजूद, टिंगबुंग मठ सिक्किम की बौद्ध पहचान का सार प्रस्तुत करता है—भक्ति, संस्कृति और प्रकृति का एक संतुलित मिश्रण।" } },
  { name: "Burtuk Monastery", 
    files: { english: "audios/english/Burtuk.mp3", hindi: "audios/hindi/Burtuk.mp3" }
,
    captions: { english: "**Burtuk Monastery**, also known as **Burtuk Ugen Pema Choling Tamu Gonpa**, is a significant Buddhist monastery located in East Sikkim, India. Established in **2000** by the **All Sikkim Gurung Tamu Buddhist Association**, it serves as a spiritual center for the Gurung and Tamu communities in the region. The monastery follows the **Nyingma** sect of Tibetan Buddhism and is dedicated to the teachings of Guru Padmasambhava, also known as Guru Rinpoche. The name Ugen Pema Choling translates to The Lotus of Ugen, reflecting the monastery's deep connection to the lotus symbolism in Buddhist teachings. Situated in the serene village of Burtuk, the monastery offers a tranquil environment conducive to meditation and spiritual practice. It is also a hub for cultural activities, preserving and promoting the rich traditions of the Gurung and Tamu communities. The monastery's establishment has played a pivotal role in strengthening the Buddhist heritage and community ties in the region.In addition to its religious functions, Burtuk Monastery is involved in various community welfare initiatives, including educational programs and support for local development. The monastery's commitment to both spiritual and social well-being underscores its integral role in the fabric of Sikkimese society. For visitors, Burtuk Monastery offers a unique opportunity to experience the spiritual and cultural richness of Sikkim. Its serene setting, coupled with its active role in community development, makes it a noteworthy destination for those interested in exploring the Buddhist traditions and community life of the region.", 
        hindi: "बुर्तुक मठ, जिसे बुर्तुक उगेन पेमा चोलिंग तामु गोम्पा भी कहा जाता है, भारत के पूर्वी सिक्किम में स्थित एक महत्वपूर्ण बौद्ध मठ है। इसकी स्थापना 2000 में ऑल सिक्किम गुरुङ तामु बौद्ध एसोसिएशन द्वारा की गई थी और यह क्षेत्र में गुरुङ और तामु समुदायों के लिए एक आध्यात्मिक केंद्र के रूप में कार्य करता है।मठ तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय का अनुसरण करता है और इसे गुरु पद्मसंभव (गुरु रिनपोचे) की शिक्षाओं को समर्पित किया गया है। उगेन पेमा चोलिंग का अर्थ है उगेन का कमल, जो बौद्ध शिक्षाओं में कमल प्रतीकवाद के साथ मठ के गहरे संबंध को दर्शाता है।शांतिपूर्ण बुर्तुक गाँव में स्थित, यह मठ ध्यान और आध्यात्मिक साधना के लिए एक शांत वातावरण प्रदान करता है। यह सांस्कृतिक गतिविधियों का भी केंद्र है, जो गुरुङ और तामु समुदायों की समृद्ध परंपराओं को संरक्षित और प्रचारित करता है। मठ की स्थापना ने क्षेत्र में बौद्ध विरासत और सामुदायिक संबंधों को मजबूत करने में महत्वपूर्ण भूमिका निभाई है।धार्मिक कार्यों के अलावा, बुर्तुक मठ शैक्षिक कार्यक्रमों और स्थानीय विकास समर्थन सहित विभिन्न सामुदायिक कल्याण पहलों में भी सक्रिय है। आध्यात्मिक और सामाजिक कल्याण के प्रति मठ की प्रतिबद्धता इसे सिक्किम के समाज में एक अभिन्न भाग बनाती है।पर्यटकों के लिए, बुर्तुक मठ सिक्किम की आध्यात्मिक और सांस्कृतिक समृद्धि का अनुभव करने का एक अनूठा अवसर प्रदान करता है। इसका शांत वातावरण और सामुदायिक विकास में सक्रिय योगदान इसे उन लोगों के लिए एक महत्वपूर्ण गंतव्य बनाता है, जो क्षेत्र की बौद्ध परंपराओं और सामुदायिक जीवन का अध्ययन करना चाहते हैं।" } },
  { name: "Wok Parbang Monastery", 
    files: { english: "audios/english/Wok.mp3", hindi: "audios/hindi/Wok.mp3" }
,
    captions: 
    { english: "Wok Pabong Samtenling Monastery, established in 1915 by Lama Pema Namgyal and Duknam Lama, is a significant Buddhist monastery located in the southern part of Sikkim, India. Situated approximately 5 kilometers from Namchi, the district headquarters, the monastery serves as a spiritual center for the local community and visitors alike. It is affiliated with the Nyingma sect of Tibetan Buddhism and follows traditional practices and rituals. The monastery's architecture reflects traditional Tibetan designs, featuring intricately painted walls, vibrant murals, and statues of various Buddhist deities. These artistic elements not only enhance the spiritual ambiance but also serve as visual narratives of Buddhist teachings and legends. Wok Pabong Samtenling Monastery continues to serve as a center for Buddhist teachings and practices, attracting pilgrims and tourists alike who seek spiritual solace and a deeper understanding of Sikkim's rich cultural heritage. The serene environment, coupled with the monastery's historical and spiritual importance, makes it a noteworthy destination for those interested in exploring the Buddhist traditions of the region. Visitors to the monastery can also explore the surrounding landscapes, which offer panoramic views of the lush greenery and distant mountains, enhancing the spiritual ambiance of the site. The monastery's commitment to preserving and promoting Buddhist traditions underscores its integral role in the cultural and spiritual fabric of Sikkim.",
         hindi: "वोक पाबोंग संतेनलिंग मठ, जिसकी स्थापना 1915 में लामा पेमा नमग्याल और डुकनाम लामा द्वारा की गई थी, भारत के सिक्किम के दक्षिणी हिस्से में स्थित एक महत्वपूर्ण बौद्ध मठ है। यह मठ जिला मुख्यालय नामची से लगभग 5 किलोमीटर की दूरी पर स्थित है और स्थानीय समुदाय तथा आगंतुकों दोनों के लिए एक आध्यात्मिक केंद्र के रूप में कार्य करता है।मठ तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है और पारंपरिक प्रथाओं और अनुष्ठानों का पालन करता है। मठ की वास्तुकला पारंपरिक तिब्बती डिज़ाइनों को दर्शाती है, जिसमें बारीक चित्रित दीवारें, जीवंत भित्ति चित्र और विभिन्न बौद्ध देवताओं की मूर्तियाँ शामिल हैं। ये कलात्मक तत्व न केवल आध्यात्मिक वातावरण को समृद्ध करते हैं, बल्कि बौद्ध शिक्षाओं और कथाओं की दृश्य कथा भी प्रस्तुत करते हैं।वोक पाबोंग संतेनलिंग मठ आज भी बौद्ध शिक्षाओं और साधनाओं का केंद्र बना हुआ है, जो श्रद्धालुओं और पर्यटकों को आध्यात्मिक शांति और सिक्किम की समृद्ध सांस्कृतिक विरासत की गहरी समझ प्रदान करता है। मठ का शांत वातावरण, ऐतिहासिक और आध्यात्मिक महत्व के साथ मिलकर इसे उन लोगों के लिए एक महत्वपूर्ण गंतव्य बनाता है, जो क्षेत्र की बौद्ध परंपराओं का अनुभव करना चाहते हैं।मठ के आगंतुक आसपास के प्राकृतिक दृश्यों का भी अन्वेषण कर सकते हैं, जो हरे-भरे वातावरण और दूरस्थ पहाड़ों के मनोरम दृश्य प्रस्तुत करते हैं, जिससे स्थल का आध्यात्मिक माहौल और भी प्रबल होता है। बौद्ध परंपराओं के संरक्षण और प्रचार में मठ की प्रतिबद्धता इसे सिक्किम की सांस्कृतिक और आध्यात्मिक संरचना में एक अभिन्न भूमिका प्रदान करती है।" } },
  { name: "Mangbru Monastery", 
    files: { english: "audios/english/Mangbru.mp3", hindi: "audios/hindi/Mangbru.mp3" }
,
    captions: 
    { english: "**Mangbru Monastery**, also known as **Mangbro Gonpa**, is a significant Buddhist monastery located above Kewzing Bazaar in South Sikkim, India. Established in **1790** by Lama Athyok, the monastery follows the **Nyingma** sect of Tibetan Buddhism and has played a pivotal role in preserving the region's spiritual heritage. The monastery's historical significance is underscored by its strategic location. During the 19th century, the Bhutanese army utilized this area for military purposes, and remnants of their bunkers and outposts can still be observed near the monastery. In terms of architecture, the monastery was renovated in **1850** to repair earthquake damages. However, after further deterioration, the original structure was demolished, and a new monastery was constructed in **2003**.Visitors to Mangbru Monastery can explore its serene surroundings, which include **eight ancient stone stupas** believed to have been erected by the lamas to ward off evil spirits. These stupas add to the spiritual ambiance of the area. For those interested in experiencing the rich spiritual and cultural heritage of Sikkim, Mangbru Monastery offers a tranquil and historically rich destination.",
         hindi: "मैंगब्रू मठ, जिसे मैंगब्रो गोम्पा भी कहा जाता है, भारत के सिक्किम के दक्षिणी हिस्से में केवज़िंग बाज़ार के ऊपर स्थित एक महत्वपूर्ण बौद्ध मठ है। इसकी स्थापना 1790 में लामा अथ्योर्क द्वारा की गई थी। मठ तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय का अनुसरण करता है और क्षेत्र की आध्यात्मिक विरासत को संरक्षित रखने में एक महत्वपूर्ण भूमिका निभाता है।मठ का ऐतिहासिक महत्व इसके रणनीतिक स्थान से भी स्पष्ट होता है। 19वीं शताब्दी में, भूटानी सेना ने इस क्षेत्र का सैन्य उपयोग किया था और मठ के पास अब भी उनके बंकर और चौकियों के अवशेष देखे जा सकते हैं।वास्तुकला की दृष्टि से, मठ को 1850 में भूकंप के नुकसान की मरम्मत के लिए नवीनीकरण किया गया था। हालांकि, आगे के क्षरण के कारण मूल संरचना को ध्वस्त कर दिया गया और 2003 में एक नया मठ निर्मित किया गया।मैंगब्रू मठ के आगंतुक इसके शांत वातावरण का आनंद ले सकते हैं, जिसमें आठ प्राचीन पत्थर स्तूप शामिल हैं, जिन्हें कहा जाता है कि बुरी आत्माओं को दूर रखने के लिए लामाों ने स्थापित किया था। ये स्तूप क्षेत्र के आध्यात्मिक माहौल को और भी प्रबल बनाते हैं।सिक्किम की समृद्ध आध्यात्मिक और सांस्कृतिक विरासत का अनुभव करने के इच्छुक लोगों के लिए, मैंगब्रू मठ एक शांत और ऐतिहासिक रूप से समृद्ध गंतव्य प्रदान करता है।" } },
  { name: "Tsungthang Monastery",
     files: { english: "audios/english/Tsungthang.mp3", hindi: "audios/hindi/Tsungthang.mp3" }
,
    captions:
     { english: "Tsungthang Monastery, also known as Tsun Hang Rigdzin Choeling Gonpa, is a significant Buddhist monastery located in Chungthang, North Sikkim, India. Established in 1788 by Lepcha Buddhists, it stands as a testament to the region's rich spiritual heritage. The monastery is affiliated with the Nyingma sect of Tibetan Buddhism and holds historical importance in the cultural landscape of Sikkim. Situated at the confluence of the Lachen and Lachung rivers, which merge to form the Teesta River, Chungthang is a town of strategic and spiritual significance. The monastery's location amidst lush forests and serene landscapes adds to its tranquil ambiance, making it a place of reflection and meditation. Over the centuries, Tsungthang Monastery has undergone various renovations to preserve its structural integrity and spiritual essence. The monastery continues to serve as a center for Buddhist teachings and practices, attracting pilgrims and visitors seeking spiritual solace. Its historical significance and serene environment make it a noteworthy destination for those interested in exploring the Buddhist heritage of Sikkim.",
         hindi: "सुनथांग मठ, जिसे ट्सुन हांग रिगडज़िन चोएलिंग गोम्पा भी कहा जाता है, भारत के सिक्किम के उत्तर हिस्से में चुंगथांग में स्थित एक महत्वपूर्ण बौद्ध मठ है। इसकी स्थापना 1788 में लेप्चा बौद्धों द्वारा की गई थी और यह क्षेत्र की समृद्ध आध्यात्मिक विरासत का प्रतीक है।मठ तिब्बती बौद्ध धर्म के निंगमा सम्प्रदाय से संबंधित है और सिक्किम के सांस्कृतिक परिदृश्य में इसका ऐतिहासिक महत्व है। यह मठ लाचेन और लचुंग नदियों के संगम स्थल पर स्थित है, जो मिलकर तीस्ता नदी का निर्माण करती हैं। चुंगथांग एक ऐसा शहर है जिसका रणनीतिक और आध्यात्मिक महत्व दोनों हैं।मठ का स्थान घने जंगलों और शांत प्राकृतिक वातावरण में होने के कारण इसका वातावरण अत्यंत सुकूनदायक और ध्यान के लिए उपयुक्त है।सदियों के दौरान, सुनथांग मठ ने अपनी संरचनात्मक अखंडता और आध्यात्मिक सार को बनाए रखने के लिए कई बार नवीनीकरण किया है। मठ आज भी बौद्ध शिक्षाओं और साधनाओं का केंद्र बना हुआ है, और श्रद्धालु तथा पर्यटक आध्यात्मिक शांति के लिए यहाँ आते हैं।इसके ऐतिहासिक महत्व और शांत वातावरण के कारण, सुनथांग मठ सिक्किम की बौद्ध विरासत का अनुभव करने के इच्छुक लोगों के लिए एक विशेष और महत्वपूर्ण गंतव्य है।" } }
];

// DOM elements
const monasteryList = document.getElementById("monasteryList");
const audioPlayer = document.getElementById("audioPlayer");
const audioSource = document.getElementById("audioSource");
const caption = document.getElementById("caption");
const languageSelector = document.getElementById("languageSelector");

// Default language
let currentLanguage = "english";

// Change language on dropdown select
languageSelector.addEventListener("change", (e) => {
  currentLanguage = e.target.value;
});

// Create buttons dynamically
monasteries.forEach(monastery => {
  const btn = document.createElement("button");
  btn.innerText = monastery.name;
  btn.onclick = () => {
    caption.innerText = ""; // reset caption
    audioSource.src = monastery.files[currentLanguage];
    audioPlayer.load();
    audioPlayer.play();

    // Show caption once audio starts
    audioPlayer.onplay = () => {
      caption.innerText = monastery.captions[currentLanguage];
    };
  };
  monasteryList.appendChild(btn);
});